### ISSUE TITLE
Geary segfault on start

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#1013]
VERSION_ID=30340

```
$ geary -d
 [deb] 19:40:05 0.000446 GLib-GIO: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
 [msg] 19:40:05 0.061059 geary: geary-application.vala:706: Geary 3.34-dev (3.34-dev) prefix=/usr exec_dir=/usr/bin is_installed=true
 [deb] 19:40:05 0.043772 geary: null-indicator.vala:13: No messaging menu support in this build
 [deb] 19:40:05 0.000425 Gcr: starting initialize of registered modules
 [deb] 19:40:05 0.000806 Gcr: completed initialize of registered modules
 [deb] 19:40:05 0.000040 Gcr: trust store uri is: (null)
 [deb] 19:40:05 0.000022 Gcr: trust lookup uris are: pkcs11:library-description=PKCS%2311%20Kit%20Trust%20Module
 [deb] 19:40:05 0.000017 geary: application-certificate-manager.vala:71: GCR slot URIs found: false
 [deb] 19:40:05 0.003801 GLib-GIO: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’
 [deb] 19:40:05 0.077638 GLib-GIO: Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
 [deb] 19:40:05 0.001244 GLib-GIO: _g_io_module_get_default: Found default implementation networkmanager (GNetworkMonitorNM) for ‘gio-network-monitor’
*[wrn] 19:40:05 0.072884 GLib-GObject: cannot register existing type 'FolksSmallSet'
![crt] 19:40:05 0.000048 GLib-GObject: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
![crt] 19:40:05 0.000020 GLib-GObject: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
![crt] 19:40:05 0.000016 GLib-GObject: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
![crt] 19:40:05 0.000015 GLib-GObject: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
![crt] 19:40:05 0.000015 GLib: g_once_init_leave: assertion 'result != 0' failed
![crt] 19:40:05 0.000015 GLib-GObject: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault (core dumped)
```

**Comment by paulcarroty** [comment]
Crashes with new update too.

**Comment by mrkz** [comment]
GDB backtrace shows the following:

```bash
(gdb) bt
#0  0x00007f5153f144ba in folks_small_set_configure
    (item_equals_data_free=<optimized out>, item_equals_data=<optimized out>, item_equals=<optimized out>, item_hash_data_free=<optimized out>, item_hash_data=<optimized out>, item_hash=<optimized out>, item_free=<optimized out>, item_dup=<optimized out>, item_type=<optimized out>, self=<optimized out>) at ../folks/small-set.c:78
#1  0x00007f5153f144ba in folks_small_set_new
    (item_type=0x40 [gchararray], item_dup=<optimized out>, item_free=0x7f51cb809680 <g_free>, item_hash=0x0, item_hash_data=0x0, item_hash_data_free=0x0, item_equals=0x0, item_equals_data=0x0, item_equals_data_free=0x0) at ../folks/small-set.c:287
#2  0x00007f5153f2fd36 in edsf_persona_store_real_prepare_co (_data_=0x5622e89ee520) at ../backends/eds/lib/edsf-persona-store.vala:826
#3  0x00007f51cb33f4a3 in g_simple_async_result_complete (simple=0x5622e8a3ed00 [GSimpleAsyncResult]) at ../gio/gsimpleasyncresult.c:802
#4  0x00007f51cb33f607 in complete_in_idle_cb_for_thread (_data=0x5622e79ecb60) at ../gio/gsimpleasyncresult.c:873
#5  0x00007f51cb814515 in g_main_dispatch (context=0x5622e77bd770) at ../glib/gmain.c:3189
#6  0x00007f51cb814515 in g_main_context_dispatch (context=0x5622e77bd770) at ../glib/gmain.c:3854
#7  0x00007f51cb814d70 in g_main_context_iterate.isra.0.lto_priv.0
    (context=0x5622e77bd770, block=<optimized out>, dispatch=<optimized out>, self=<optimized out>) at ../glib/gmain.c:3927
#8  0x00007f51cb7ae533 in g_main_loop_run (loop=0x5622e87fe5c0) at ../glib/gmain.c:4123
#9  0x00007f51cad8db82 in gtk_dialog_run (dialog=0x5622e78965f0 [AccountsEditor]) at gtkdialog.c:1398
#10 0x00005622e676f253 in geary_application_show_accounts (self=0x5622e77a8120 [GearyApplication])
    at ../src/client/application/geary-application.vala:295
#11 0x00005622e675e70c in geary_controller_open_async_co (_data_=0x5622e78cdd30) at ../src/client/application/geary-controller.vala:383
#12 0x00007f51cb327971 in g_task_return_now (task=0x5622e7ea0190 [GTask]) at ../gio/gtask.c:1209
#13 0x00007f51cb327971 in g_task_return.part.0.lto_priv.0 (task=0x5622e7ea0190 [GTask], type=<optimized out>) at ../gio/gtask.c:1278
#14 0x00005622e671a12a in accounts_manager_load_accounts_co (_data_=0x5622e7db3970) at ../src/client/accounts/accounts-manager.vala:223
#15 0x00007f51cb324e12 in g_task_return_now (task=0x5622e7ea1550 [GTask]) at ../gio/gasyncresult.c:120
#16 0x00007f51cb324e12 in complete_in_idle_cb (task=0x5622e7ea1550) at ../gio/gtask.c:1223
#17 0x00007f51cb814515 in g_main_dispatch (context=0x5622e77bd770) at ../glib/gmain.c:3189
#18 0x00007f51cb814515 in g_main_context_dispatch (context=0x5622e77bd770) at ../glib/gmain.c:3854
#19 0x00007f51cb814d70 in g_main_context_iterate.isra.0.lto_priv.0
    (context=0x5622e77bd770, block=<optimized out>, dispatch=<optimized out>, self=<optimized out>) at ../glib/gmain.c:3927
#20 0x00007f51cb817f0f in g_main_context_iteration (context=context@entry=0x5622e77bd770, may_block=may_block@entry=1) at ../glib/gthread.c:1003
#21 0x00007f51cb2f39dd in g_application_run (application=0x5622e77a8120 [GearyApplication], argc=<optimized out>, argv=<optimized out>)
    at ../gio/gapplication.c:2516
#22 0x00005622e63d6b56 in _vala_main (args_length1=2, args=0x7ffd1274b4f8) at ../src/client/application/main.vala:33
#23 0x00005622e63d6b56 in main (argc=2, argv=0x7ffd1274b4f8) at ../src/client/application/main.vala:7
```

**Comment by mrkz** [comment]
Got the culprit to be libfolks being compiled using LTO, I pushed a new build of this GNOME library disabling LTO.

The fix should arrive for release **30500** (or later).

**Comment by mrkz** [comment]
Release **30500** is available and fixes this issue. Closing now
