### ISSUE TITLE
bleachbit for clear linux.

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1320]
bundle package request for bleachbit

https://www.bleachbit.org/download/linux

**Comment by felixg3** [comment]
I would like to support this request. installing via dnf fails, no appimage or flatpak available. Compiling from source is not trivial due to weird dependency issues

**Comment by ahkok** [comment]
```
+ python3 setup.py build
/builddir/build/BUILD/bleachbit-3.1.0/bleachbit/__init__.py:361: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if msgctxt is not None and msgctxt is not "":
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    import bleachbit
  File "/builddir/build/BUILD/bleachbit-3.1.0/bleachbit/__init__.py", line 69, in <module>
    __file__.decode(sys.getfilesystemencoding())))
AttributeError: 'str' object has no attribute 'decode'
```

This looks entirely untested... Maybe not compatible with py3.8?

**Comment by felixg3** [comment]
I am experiencing the same issues, @ahkok.

**Comment by insilications** [comment]
The "mkhon-python3" branch is running perfectly here without installation.
https://github.com/bleachbit/bleachbit/tree/mkhon-python3

**Comment by insilications** [comment]
Correction: "mkhon-python3" branch is old and buggy. Clone the py3 branch which is the correct and most updated one.

git clone --branch py3 https://github.com/bleachbit/bleachbit.git
