### ISSUE TITLE
dpdk: ModuleNotFoundError: No module named 'elftools'

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/distribution#1464]
Python exception running dpdk-pmdinfo.
Steps to reproduce:

<pre>
$ dpdk-pmdinfo
Traceback (most recent call last):
  File "/usr/bin/dpdk-pmdinfo", line 16, in <module>
    from elftools.common.exceptions import ELFError
ModuleNotFoundError: No module named 'elftools'
</pre>

**Comment by ahkok** [comment]
Looks like we miss this dependency entirely.

**Comment by grantcurell** [comment]
Is there a fix action for this? Installing elftools doesn't seem to resolve the issue:

```
[root@dpdkdemo dpdk-19.08]# pip3 install elftools
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Requirement already satisfied: elftools in /usr/local/lib64/python3.6/site-packages
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib64/python3.6/site-packages (from elftools)
Requirement already satisfied: matplotlib>=2.2.3 in /usr/local/lib64/python3.6/site-packages (from elftools)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib64/python3.6/site-packages (from matplotlib>=2.2.3->elftools)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/site-packages (from matplotlib>=2.2.3->elftools)
Requirement already satisfied: python-dateutil>=2.1 in /usr/lib/python3.6/site-packages (from matplotlib>=2.2.3->elftools)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/site-packages (from matplotlib>=2.2.3->elftools)
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.2.3->elftools)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.6/site-packages (from python-dateutil>=2.1->matplotlib>=2.2.3->elftools)
[root@dpdkdemo dpdk-19.08]# python3.6 ./install/share/dpdk/usertools/dpdk-pmdinfo.py
Traceback (most recent call last):
  File "./install/share/dpdk/usertools/dpdk-pmdinfo.py", line 16, in <module>
    from elftools.common.exceptions import ELFError
ModuleNotFoundError: No module named 'elftools'
```

I'm running on RHEL8.

**Comment by grantcurell** [comment]
If anyone else runs into this, you have to run `pip3 install pyelftools` to get it running. elftools isn't what you want.

**Comment by vtlrazin** [comment]
For Ubuntu:

`apt-get install -y python3-pyelftools python-pyelftools`

Good luck...

**Comment by saintofinternet** [comment]
anything that we can do on a Windows machine?

**Comment by thiagomacieira** [comment]
What does a Windows machine have to do with anything?

Anyway, this is believed to have been fixed by https://github.com/clearlinux-pkgs/dpdk/releases/tag/19.05-48
