### ISSUE TITLE
BBC biolatency yields an FIleNotFoundError runtime exception

### ISSUE THREAD

**Issue by lsandov1** [clearlinux/distribution#1544]
While trying to run the following command, it produces the below log

```
 sudo /usr/share/bcc/tools/biolatency -mT 1 5
Traceback (most recent call last):
  File "/usr/share/bcc/tools/biolatency", line 138, in <module>
    if BPF.get_kprobe_functions(b'blk_start_request'):
  File "/usr/lib/python3.7/site-packages/bcc/__init__.py", line 539, in get_kprobe_functions
    with open("%s/../kprobes/blacklist" % TRACEFS, "rb") as blacklist_f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/tracing/../kprobes/blacklist'
```

Looks to me that some kernel config is missing but I am not expert on BPF so opening this question to the experts.

**Comment by ahkok** [comment]
```
sudo /usr/share/bcc/tools/biolatency -mT 1 5
modprobe: FATAL: Module kheaders not found in directory /lib/modules/5.3.7-853.native
Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module)
chdir(/lib/modules/5.3.7-853.native/build): No such file or directory
Traceback (most recent call last):
  File "/usr/share/bcc/tools/biolatency", line 134, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3.8/site-packages/bcc/__init__.py", line 347, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

**Comment by ahkok** [comment]
`bcc` package

**Comment by miguelinux** [comment]
IKHEADERS is "Enable kernel headers through /sys/kernel/kheaders.tar.xz"    
The help said
> This option enables access to the in-kernel headers that are generated during
> the build process. These can be used to build eBPF tracing programs,  
> or similar programs.  If you build the headers as a module, a module called
> kheaders.ko is built which can be loaded on-demand to get access to headers.

**Comment by ahkok** [comment]
@bwarden and @miguelinux can you two figure out a solution for this sort of problem? This package needs to compile a custom module on demand. perhaps this is supported by LTS kernels ...?

**Comment by miguelinux** [comment]
out-of-tree modules are available on LTS and -natives kernels, but let
me figure out a better solution for this specific  use case.

**Comment by mythi** [comment]
I've played with eBPF. No out-of-tree modules are needed. 

The problem is that the kernel headers are not found in *normal* paths. BCC, tries hard to find them and the last resort is to see if `kheaders.tar.gz` is available.

If @lsandov1 uses a kernel that has `-dev` available just set the env (I don't recall the name) variable BCC uses to point to the right headers.

**Comment by lsandov1** [comment]
@mythi I tried installing manually the linux-dev [1], then setting `BCC_KERNEL_SOURCE=/usr/lib/modules/5.3.8-854.native/build/` [2] and `sudo -E` the biolatency cmd. It did not work. 

[1] [linux-dev](http://kojiclear.jf.intel.com/kojifiles/packages/linux/5.3.8/854/x86_64/linux-dev-5.3.8-854.x86_64.rpm)
[2] [BCC_KERNEL_SOURCE](https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#1-kernel-source-directory)

In the other hard, `swupd search-file kheaders.tar.gz` does not throw any result.

**Comment by mythi** [comment]
I did not read the original error carefully. Some of the tools depend on kprobes that is not enabled in the kernels.
