### ISSUE TITLE
firewalld cant be started, missing python module: six

### ISSUE THREAD

**Issue by fcicq** [clearlinux/distribution#1572]
swupd info
Distribution:      Clear Linux OS
Installed version: 31890

install:
sudo swupd bundle-add firewalld

sudo firewalld --nofork --debug
```Traceback (most recent call last):
  File "/usr/bin/firewalld", line 194, in <module>
    main()
  File "/usr/bin/firewalld", line 189, in main
    startup(args)
  File "/usr/bin/firewalld", line 142, in startup
    from firewall.server import server
  File "/usr/lib/python3.8/site-packages/firewall/server/server.py", line 40, in <module>
    import slip.dbus
  File "/usr/lib/python3.8/site-packages/slip/dbus/__init__.py", line 8, in <module>
    from . import service
  File "/usr/lib/python3.8/site-packages/slip/dbus/service.py", line 30, in <module>
    from six import with_metaclass
ModuleNotFoundError: No module named 'six'
```

**Comment by fcicq** [comment]
temporary solution: sudo pip3 install six
then nft binary is missing: sudo swupd bundle-add network-basic

remaining is same as #1032

**Comment by puneetse** [comment]
Looks like `six` is required by `slip` so it would make sense to add it as a dependency there is instead of firewalld. `slip` is already required by firewalld.
