### ISSUE TITLE
 Cura dies on startup due to PyCapsule_GetPointer called with incorrect name

### ISSUE THREAD

**Issue by bwarden** [clearlinux/distribution#1688]
Moving past the now-resolved #1650, Cura dies differently at startup:

```
$ cura
/usr/lib/python3.8/site-packages/UM/PluginRegistry.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/cura/CuraApplication.py", line 26, in <module>
    from UM.Qt.QtApplication import QtApplication  # The class we're inheriting from.
  File "/usr/lib/python3.8/site-packages/UM/Qt/QtApplication.py", line 17, in <module>
    from UM.Backend.Backend import Backend #For typing.
  File "/usr/lib/python3.8/site-packages/UM/Backend/Backend.py", line 12, in <module>
    from UM.Backend.SignalSocket import SignalSocket
  File "/usr/lib/python3.8/site-packages/UM/Backend/SignalSocket.py", line 4, in <module>
    import Arcus
ValueError: PyCapsule_GetPointer called with incorrect name

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/cura", line 143, in <module>
    import Arcus #@UnusedImport
ModuleNotFoundError: No module named 'sip'
```

**Comment by bwarden** [comment]
Looks like it may be related to these:
https://bugzilla.redhat.com/show_bug.cgi?id=1601917
https://src.fedoraproject.org/rpms/libarcus/pull-request/2#request_diff

Results are promising if I make the same change to both `libArcus` and `libSavitar`.

**Comment by bwarden** [comment]
Looks like that solved it. Fix should be in 32230 or later.
