### ISSUE TITLE
Openshot doesn't work...

### ISSUE THREAD

**Issue by pixelgeek** [clearlinux/distribution#1957]
clearuser@cnorman-clr/ $ openshot-qt
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/openshot_qt/launch.py", line 47, in <module>
    from classes import info
ModuleNotFoundError: No module named 'classes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.5.1', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/openshot_qt/launch.py", line 52, in <module>
    from classes import info
  File "/usr/lib/python3.8/site-packages/openshot_qt/classes/info.py", line 30, in <module>
    from PyQt5.QtCore import QDir
ModuleNotFoundError: No module named 'PyQt5.sip'

I don't think this is the same as bug 1922, although that might need to be revisited too?

**Comment by ahkok** [comment]
This isn't the same as #1922 though. it's a different dependency for sure. We might not even have the needed python files ...

**Comment by ahkok** [comment]
This looks like a bigger problem than initially estimated PyQt5-SIP is published under the `SIP` license but despite claims it's similar to Python's license, I cannot *find it*. It's not even in the PyQt5-SIP project source code despite claims it should be in the LICENSE file (there is no such file!).

**Comment by ahkok** [comment]
Or we're not building PyQt5 correctly... hmmm
