### ISSUE TITLE
gdb failed to load python module with C extension

### ISSUE THREAD

**Issue by chaoyi** [clearlinux/distribution#2234]
**version**: 34130
**steps to reproduce**:
```
❯ /usr/bin/gdb --nx
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-generic-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) python import random
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/random.py", line 49, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: /usr/lib/python3.9/lib-dynload/math.cpython-39-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type
Error while executing Python code.
```
**expected outcome**:
python module loaded without error

**Comment by lebensterben** [comment]
confirmed

**Comment by topcat001** [comment]
I noticed this while trying to load `gdb-dashboard`. In my case it was `import math` which caused the fault.

**Comment by topcat001** [comment]
This seems to have some connection with this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1585201. Posting here in case it helps.

 The tl;dr version is that the C extension is built without `--enable-shared` passed to `configure` so it is not linked with `libpython3.9.so`, instead expecting to find symbols in either the monolithic python (as confirmed by `ldd /usr/bin/python`) or in the embedding application's global namespace.
 
 gdb probably just `dlopen`s the extension directly without also loading the python library with `RT_GLOBAL` which results in undefined symbols.

**Comment by chaoyi** [comment]
I ran into it using pwndbg.  I also think it has something to do with python because after compiling python as well as gdb then it loaded.  Must related to custom built python.

**Comment by insilications** [comment]
Seems like the custom python needs to be fixed @fenrus75 @phmccarty

**Comment by insilications** [comment]
Has anyone managed to rebuild the python3 clr package in order to fix this and keep the avx2 optimizations? cc @lebensterben

**Comment by lebensterben** [comment]
Mystery solved:

On platform with avx2, it should use
`PYTHON=/usr/bin/haswell/python3` instead.

https://github.com/clearlinux-pkgs/gdb/blob/626b103356522005abbd1adaa04af2e8828932cf/configure#L1

**Comment by insilications** [comment]
Went to https://sourceware.org/git/?p=binutils-gdb.git, checked the commits, found tons of related problems. I've decided to simply brute force it:

export LDFLAGS="Wl,--whole-archive /usr/lib64/haswell/libpython3.9.so -Wl,--no-whole-archive"

It works now perfectly. Just open the binutils-gdb/gdb/configure file and search for Workaround+http://bugs.python.org. It's pure chaos.

**Comment by fenrus75** [comment]
if that's all there is to it then it's easy to fix ;)

I'll add this

**Comment by topcat001** [comment]
Is the `--whole-archive` option really necessary? If the goal is to force the shared python to load during gdb startup (and expose its symbols), just specifying the shared object should be enough?  I thought it only worked on `.a` files?

**Comment by fenrus75** [comment]
it's likely not required. it's not going to hurt either

**Comment by topcat001** [comment]
Sounds good, and thank you for your work!

**Comment by insilications** [comment]
You are correct. It makes no sense, but I thought it would confuse autotools and mess with the linking precedence and force libpython to be available in RTDL_GLOBAL.

@fenrus75 
I messed up. My placebo fix was the result of me accidentally autospec'ing the GDB 11.0.50 from the latest git. I tested again: the problem lies with GDB 10.1 release. I wonder if a simple patch would fix this, if we could find the commits.

**Comment by fenrus75** [comment]
so there is one detail I also had to fix; we use LD_AS_NEEDED by default, which removes .so files you link in but don't use...
I had to turn that off for gdb since gdb does not use the python lib itself.

(we do this since on average, autoconf and pkgconfig add a ton of false dependencies costing memory and startup time... but well, it breaks in this case)

**Comment by mdhorn** [comment]
Workaround released in 34380

**Comment by philbyjohn** [comment]
> The tl;dr version is that the C extension is built without `--enable-shared` passed to `configure`

I tried to pass "--enable-shared" at the time of configuration but it still throws error.

$ PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.8.18

(gdb) source ~/.gdb-dashboard 
Traceback (most recent call last):
  File "<string>", line 33, in <module>
ImportError: /home/philby/.pyenv/versions/3.8.18/lib/python3.8/lib-dynload/math.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type
~/.gdb-dashboard:2362: Error in sourced command file:
Error while executing Python code.

I too am trying to install gdb-dashboard. No luck so far. Since this version of the gdb is provided by ARM, cannot build it.

**Comment by thiagomacieira** [comment]
/home/philby/.pyenv implies it's something you installed and compiled. It's not compatible with the host Python. You need to rebuild it.

**Comment by fenrus75** [comment]
Clear Linux ships with python 3.12 not python 3.8 so something is horribly
wrong here --- likely some kind of mix of Clear Linux provided bits and 3rd
party bits that aren't done very well
