### ISSUE TITLE
Tensorflow RNN broken

### ISSUE THREAD

**Issue by danielsGitStuff** [clearlinux/distribution#2328]
Current OS version: 34470
CPU is i7 8550u 

installed bundles:
```
machine-learning-tensorflow
python-data-science
python-extras
```

versions are:
```
python: 3.9.2
numpy: 1.20.2
tensorflow: 2.3.1
```
These versions do not appear together outside Clear Linux. Tensorflow starts being compatible to Python 3.9 with version 2.5.0rc0 (which currently wants numpy in version 1.19.2)

Just start python in a terminal and paste this code:
```
from tensorflow.python.keras import Sequential
import tensorflow as tf
model: Sequential = Sequential([
    tf.keras.layers.GRU(3, input_shape=(5,6)),
    tf.keras.layers.Dense(1)
])
```
Expectation:
No crash.

Actual result:
```
2021-04-08 11:26:13.674548: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 1999965000 Hz
2021-04-08 11:26:13.675199: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x559ee0c2bb00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-08 11:26:13.675229: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/sequential.py", line 142, in __init__
    self.add(layer)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/sequential.py", line 206, in add
    layer(x)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent.py", line 659, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 925, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1117, in _functional_construction_call
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent_v2.py", line 409, in call
    inputs, initial_state, _ = self._process_inputs(inputs, initial_state, None)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent.py", line 858, in _process_inputs
    initial_state = self.get_initial_state(inputs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent.py", line 641, in get_initial_state
    init_state = get_initial_state_fn(
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent.py", line 1949, in get_initial_state
    return _generate_zero_filled_state_for_cell(self, inputs, batch_size, dtype)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2964, in _generate_zero_filled_state_for_cell
    return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2982, in _generate_zero_filled_state
    return create_zeros(state_size)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2977, in create_zeros
    return array_ops.zeros(init_state_size, dtype=dtype)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 2747, in wrapped
    tensor = fun(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 2794, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 2732, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 5, in prod
  File "/usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3030, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
  File "/usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 845, in __array__
    raise NotImplementedError(
NotImplementedError: Cannot convert a symbolic Tensor (gru_1/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```

Code runs fine with tensorflow 2.5.0rc0 from pypi or tensorflow 2.4.1 from pypi with Python 3.8.9.
`tf.keras.layers.LSTM` is affected by this issue too.

**Comment by phmccarty** [comment]
Thanks for the report.

We would like to update tensorflow to latest (currently 2.4.1), but having it depend on Python 3.8 is not likely, since we recently removed Python 3.8 from the distro. I will keep an eye on progress upstream to see if Python 3.9+ fixes land in a newer bugfix release of tensorflow 2.4, or if we'll need to wait until tensorflow 2.5 is released. We still have Python 3.7 in the distro but only for compatibility reasons (to support the [buildreq-spark](https://github.com/clearlinux/clr-bundles/blob/8aa3e4a986/bundles/buildreq-spark) bundle), so I would be hesitant to add another user of it, though it is technically possible.

Also, clearly our test coverage for tensorflow is not good enough, since we didn't catch this problem. I'll look improvements we can make there.

**Comment by phmccarty** [comment]
I started work on updating tensorflow to 2.5 last week and made more progress this week. Both tensorflow and tensorboard are building successfully with bazel 3.7.2, though I haven't tested the resulting binaries yet. I'll start working through the other miscellaneous tensorflow-* packages next week and see what additional changes might be needed regarding third-party, system-provided dependencies (numpy, etc.).

**Comment by phmccarty** [comment]
Tensorflow was removed from Clear Linux OS in November, so we can close this request.
