### ISSUE TITLE
No module named 'PyQt5.sip'

### ISSUE THREAD

**Issue by rtlprmft** [clearlinux/distribution#2375]
Cura 4.8 (4.8.0~202101281751~rev5032~pkg375~ubuntu20.04.1):
Traceback (most recent call last):
  File "/usr/bin/cura.real", line 25, in <module>
    import pynest2d # @UnusedImport
ModuleNotFoundError: No module named 'PyQt5.sip'

Cura 4.10 (4.10~202106111837~rev3262~pkg387~ubuntu20.04.1)
/usr/lib/python3/dist-packages/UM/PluginRegistry.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/cura/CuraApplication.py", line 35, in <module>
    from UM.Qt.QtApplication import QtApplication  # The class we're inheriting from.
  File "/usr/lib/python3/dist-packages/UM/Qt/QtApplication.py", line 19, in <module>
    from UM.Backend.Backend import Backend #For typing.
  File "/usr/lib/python3/dist-packages/UM/Backend/Backend.py", line 12, in <module>
    from UM.Backend.SignalSocket import SignalSocket
  File "/usr/lib/python3/dist-packages/UM/Backend/SignalSocket.py", line 4, in <module>
    import Arcus
ModuleNotFoundError: No module named 'PyQt5.sip'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/cura.real", line 187, in <module>
    from cura.CuraApplication import CuraApplication
  File "/usr/lib/python3/dist-packages/cura/CuraApplication.py", line 35, in <module>
    from UM.Qt.QtApplication import QtApplication  # The class we're inheriting from.
  File "/usr/lib/python3/dist-packages/UM/Qt/QtApplication.py", line 19, in <module>
    from UM.Backend.Backend import Backend #For typing.
  File "/usr/lib/python3/dist-packages/UM/Backend/Backend.py", line 12, in <module>
    from UM.Backend.SignalSocket import SignalSocket
  File "/usr/lib/python3/dist-packages/UM/Backend/SignalSocket.py", line 4, in <module>
    import Arcus
ModuleNotFoundError: No module named 'PyQt5.sip'

I have no experience with Python and I assume all dependencies were installed automatically. Any help is welcome.

**Comment by thiagomacieira** [comment]
> I have no experience with Python and I assume all dependencies were installed automatically. Any help is welcome.

The assumption is wrong. How did you install the application in question? Clear Linux currently has Cura 4.9, not 4.8 or 4.10 that your logs show.

**Comment by rtlprmft** [comment]
I followed the instructions here: https://thopiekar.eu/cura/ppa/. Ubuntu 20.04(LTS) ships with 4.4 which is not useful. I just updated from a version that I installed a few months ago (maybe in Jan or Feb) and got that error. Then I tried the master branch which identifies itself as 4.10 (I think just because the version number is newer than the current stable release) and got the other error.

**Comment by lebensterben** [comment]
> Ubuntu 20.04(LTS) ships with 4.4 which is not useful.

Just to clarify, this is not Ubuntu.

**Comment by thiagomacieira** [comment]
Run instead:
```sh
sudo swupd bundle-add maker-3dprinting
```

This will install Cura 4.9 on Clear Linux.
