### ISSUE TITLE
conda bundle Module Not Found Error: No module named 'conda_package_handling'

### ISSUE THREAD

**Issue by yangchino1** [clearlinux/distribution#2382]
Severity: major
System: 34770
Description: After initializtion using `conda init` and session restart, conda still cannot be used. conda command such as `list`, `install` or `create` shows the following error:
 
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/usr/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/usr/lib/python3.9/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/usr/lib/python3.9/site-packages/conda/cli/install.py", line 116, in install
        if context.use_only_tar_bz2:
      File "/usr/lib/python3.9/site-packages/conda/base/context.py", line 734, in use_only_tar_bz2
        import conda_package_handling.api
    ModuleNotFoundError: No module named 'conda_package_handling'
    ......

**Comment by lebensterben** [comment]
Upstream bug

https://github.com/conda/conda/issues/9510
