### ISSUE TITLE
devpkg-libhandy in bundles list but not in bundle_status dict

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2514]
```log
$ aps devpkg-libhandy
Traceback (most recent call last):
  File "/usr/bin/swupd-search", line 626, in <module>
    main()
  File "/usr/bin/swupd-search", line 599, in main
    do_search(term)
  File "/usr/bin/swupd-search", line 297, in do_search
    if bundle_status[term] == "Deprecated":
KeyError: 'devpkg-libhandy'
```

**Comment by nobodyatandnothing** [comment]
fixed
