### ISSUE TITLE
Cannot add HP printer in settings

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2534]
I installed Clear Linux 35720 and updated to 35740. Journalctl reports two issues when adding a printer.

**Issue 1**

The permission of the setuid helper is not correct.
 
```text
Jan 26 20:17:36 clrlinux dbus-daemon[707]: [system] Activating service name='org.opensuse.CupsPkHelper.Mechanism' requested by ':1.169' (uid=1000 pid=230506 comm="gnome-control-center ") (using servicehelper)
Jan 26 20:17:36 clrlinux dbus-daemon[707]: [system] Activated service 'org.opensuse.CupsPkHelper.Mechanism' failed: The permission of the setuid helper is not correct
Jan 26 20:17:36 clrlinux gnome-control-c[230506]: GDBus.Error:org.freedesktop.DBus.Error.Spawn.PermissionsInvalid: The permission of the setuid helper is not correct
```
```bash
$ ls -l /usr/libexec/dbus-daemon-launch-helper 
-rwxr-xr-x 2 root root 63808 Nov  5 18:34 /usr/libexec/dbus-daemon-launch-helper
```

**Issue 2**

No module named 'cupshelpers'. The Python module appears to be there, just will not import.

```text
Jan 26 20:17:55 clrlinux dbus-daemon[4379]: [session uid=1000 pid=4379] Activating service name='org.fedoraproject.Config.Printing' requested by ':1.142' (uid=1000 pid=230506 comm="gnome-control-center ")
Jan 26 20:17:55 clrlinux org.fedoraproject.Config.Printing[230576]: Traceback (most recent call last):
Jan 26 20:17:55 clrlinux org.fedoraproject.Config.Printing[230576]:   File "/usr/share/system-config-printer/scp-dbus-service.py", line 37, in <module>
Jan 26 20:17:55 clrlinux org.fedoraproject.Config.Printing[230576]:     import cupshelpers
Jan 26 20:17:55 clrlinux org.fedoraproject.Config.Printing[230576]: ModuleNotFoundError: No module named 'cupshelpers'
Jan 26 20:17:55 clrlinux dbus-daemon[4379]: [session uid=1000 pid=4379] Activated service 'org.fedoraproject.Config.Printing' failed: Process org.fedoraproject.Config.Printing exited with status 1
Jan 26 20:17:55 clrlinux gnome-control-c[230506]: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.fedoraproject.Config.Printing exited with status 1
Jan 26 20:17:55 clrlinux gnome-control-c[230506]: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.PackageKit was not provided by any .service files
Jan 26 20:17:55 clrlinux dbus-daemon[4379]: [session uid=1000 pid=4379] Activating service name='org.fedoraproject.Config.Printing' requested by ':1.142' (uid=1000 pid=230506 comm="gnome-control-center ")
Jan 26 20:17:55 clrlinux org.fedoraproject.Config.Printing[230578]: Traceback (most recent call last):
Jan 26 20:17:55 clrlinux org.fedoraproject.Config.Printing[230578]:   File "/usr/share/system-config-printer/scp-dbus-service.py", line 37, in <module>
Jan 26 20:17:55 clrlinux org.fedoraproject.Config.Printing[230578]:     import cupshelpers
Jan 26 20:17:55 clrlinux org.fedoraproject.Config.Printing[230578]: ModuleNotFoundError: No module named 'cupshelpers'
Jan 26 20:17:55 clrlinux dbus-daemon[4379]: [session uid=1000 pid=4379] Activated service 'org.fedoraproject.Config.Printing' failed: Process org.fedoraproject.Config.Printing exited with status 1
Jan 26 20:17:55 clrlinux gnome-control-c[230506]: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.fedoraproject.Config.Printing exited with status 1
Jan 26 20:17:55 clrlinux gnome-control-c[230506]: Installation of the new printer failed.
```

**Comment by marioroy** [comment]
Using Clear Linux 35750, I needed to update the permission. Afterwards I was able to add a printer by entering the IP address, click on JetDirect-Printer, select Manufacturer, and Driver.
```bash
$ sudo chmod u+s /usr/libexec/dbus-daemon-launch-helper
```
While entering the IP address the actual printer name appears in the list. However, choosing that fails with the NoduleNotFoundError: No module named 'cupshelpers'. Only the JetDirect-Printer path works.

**Comment by bryteise** [comment]
Fixed the setuid bits for the next release. The module is a bit odd though.

**Comment by bryteise** [comment]
Ah setuptools biting again, if you want a workaround you can `mv /usr/lib/python3.10/site-packages/cupshelpers-1.0-py3.10.egg/cupshelpers /usr/lib/python3.10/site-packages/` .

**Comment by bryteise** [comment]
Will be fixed in the next release.

**Comment by marioroy** [comment]
I did the workaround by moving `cupshelpers` up one directory. And that brings up another issue.
```text
Jan 27 14:16:00 clrlinux cupsd[15380]: REQUEST localhost - - "POST / HTTP/1.1" 200 2200941 CUPS-Get-PPDs -
Jan 27 14:16:00 clrlinux gnome-control-c[15283]: GDBus.Error:org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
                                                   File "/usr/share/system-config-printer/scp-dbus-service.py", line 172, in _ppds_ready
                                                     ppdname = ppdnamelist[0]
                                                 TypeError: 'dict_keys' object is not subscriptable
Jan 27 14:16:00 clrlinux gnome-control-c[15283]: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.PackageKit was not provided by an>
Jan 27 14:16:00 clrlinux gnome-control-c[15283]: GDBus.Error:org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
                                                   File "/usr/share/system-config-printer/scp-dbus-service.py", line 172, in _ppds_ready
                                                     ppdname = ppdnamelist[0]
                                                 TypeError: 'dict_keys' object is not subscriptable
Jan 27 14:16:00 clrlinux gnome-control-c[15283]: Installation of the new printer failed.
```

**Comment by marioroy** [comment]
This error too.
```text
Jan 27 14:20:35 clrlinux org.fedoraproject.Config.Printing[15656]: Error loading /etc/cupshelpers/preferreddrivers.xml: [Errno 2] No such file or directory: '/etc/cupshelpers/preferreddrivers.xml'
```

**Comment by marioroy** [comment]
I searched the internet for [preferreddrivers.xml ](https://github.com/OpenPrinting/system-config-printer/blob/master/xml/preferreddrivers.xml)and copied to `/etc/cupshelpers/preferreddrivers.xml`. Now `cupshelpers` works.

**Comment by marioroy** [comment]
The cups `ippfind` utility is also missing.
```text
Jan 27 14:20:05 clrlinux cupsd[15546]: [CGI] Unable to execute ippfind utility: No such file or directory
```

**Comment by marioroy** [comment]
@bryteise, friendly ping in the event you missed two more errors above. Missing `preferreddrivers.xml` and `ippfind`.

**Comment by bryteise** [comment]
Hrm, well we'll see if the python error shows up with the rebuild (I can hope).

For the xml file, that'll be something we can fix. I'd rather avoid to turn on avahi (hence the ippfind warning) as there is no good way I know to have it disabled by default.

**Comment by marioroy** [comment]
Great! From testing, the `preferreddrivers.xml` file is needed for `cupshelpers` to work. No problem about `ippfind`, not needed.

**Comment by bryteise** [comment]
Yep, it defaulted to putting it into /etc and we missed that it got cleaned out. I'm update the sysconfdir and you should see it in the next release (under `/usr/share/system-config-printer`).

**Comment by marioroy** [comment]
Thank you, William. This is awesome. I can now add the printer the obvious way.
