### ISSUE TITLE
emoji-picker can't run

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#2630]
```
$ emoji-picker 

(emoji-picker:6706): dconf-WARNING **: 14:57:01.930: Unable to open /root/.local/share/flatpak/exports/share/dconf/profile/user: Permission denied
Traceback (most recent call last):
  File "/usr/share/ibus-typing-booster/engine/emoji_picker.py", line 60, in <module>
    import itb_emoji
  File "/usr/share/ibus-typing-booster/engine/itb_emoji.py", line 44, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by phmccarty** [comment]
Thanks for the report. We are adding `pypi-packaging` as a manual runtime dependency for the `ibus-typing-booster` package.
