### ISSUE TITLE
Regression: /usr/bin/java crashes to SIGILL on startup

### ISSUE THREAD

**Issue by eero-t** [clearlinux/distribution#2754]
Setup:
* HW: BXT J4205
* OS: ClearLinux 37440 (or latest 37450)

Use-case/issue:
* Jenkins fails due to Java crashing on startup:
```
$ /usr/bin/java
Illegal instruction (core dumped)
```

This is regression from previously used ClearLinux 37310 version.

Java crashes due to use of instruction unsuitable for Broxton CPU in JLI:
```
$ gdb /usr/bin/java
GNU gdb (GDB) 12.1
...
(gdb) run
Starting program: /usr/bin/java 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
process 16368 is executing new program: /usr/lib/jvm/java-1.18.0/bin/java
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x00005555555480b0 in JLI_Launch () from /usr/lib/jvm/java-1.18.0/bin/../lib/libjli.so
(gdb) bt
#0  0x00005555555480b0 in JLI_Launch () from /usr/lib/jvm/java-1.18.0/bin/../lib/libjli.so
#1  0x0000555555555206 in ?? ()
#2  0x000055555531e147 in ?? () from /usr/lib64/libc.so.6
#3  0x000055555531e205 in __libc_start_main () from /usr/lib64/libc.so.6
#4  0x00005555555552a1 in ?? ()
(gdb) disassemble 0x00005555555480b0
Dump of assembler code for function JLI_Launch:
   0x0000555555546b10 <+0>:	push   %rbp
...
   0x0000555555548094 <+5508>:	je     0x55555554812d <JLI_Launch+5661>
   0x000055555554809a <+5514>:	mov    %rbx,-0x4120(%rbp)
   0x00005555555480a1 <+5521>:	movl   $0x1,-0x4118(%rbp)
   0x00005555555480ab <+5531>:	jmp    0x55555554747e <JLI_Launch+2414>
=> 0x00005555555480b0 <+5536>:	vpxor  %xmm0,%xmm0,%xmm0
   0x00005555555480b4 <+5540>:	movb   $0x0,-0x40b8(%rbp)
   0x00005555555480bb <+5547>:	movq   $0x0,-0x40c0(%rbp)
   0x00005555555480c6 <+5558>:	vmovdqa %xmm0,-0x40d0(%rbp)
```

**Comment by eero-t** [comment]
Btw. I would have filed this to ClearLinux "usrbinjava" project, but that's obviously dead (no open or closed tickets or PRs, and only few commits in 2019, none later).
