### ISSUE TITLE
ceph-volume - No module named pkg_resources

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#28]
A fresh install of Clear Linux with the storage-cluster bundle had an unusable `ceph-volume` command. This can be reproduced with:
```
# ceph-volume -h
Traceback (most recent call last):
  File "/usr/bin/ceph-volume", line 3, in <module>
    from ceph_volume import main
  File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 4,  in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```

This still occurs after updating to 21510.

**Comment by ahkok** [comment]
even worse for me:

```
$ ceph-volume
Traceback (most recent call last):
  File "/usr/bin/ceph-volume", line 3, in <module>
    from ceph_volume import main
ImportError: No module named ceph_volume
```

**Comment by fenrus75** [comment]
we need to move this lot to python 3.
legacy python is going to keep giving issue like this

**Comment by pohly** [comment]
Was fixed in the ceph packaging.
