### ISSUE TITLE
arandr fails to run due to Python getargspec deprecation

### ISSUE THREAD

**Issue by wheerdam** [clearlinux/distribution#2833]
arandr currently will not run due to getargspec function deprecation in python 3.11
```
$ arandr
Traceback (most recent call last):
  File "/usr/bin/arandr", line 41, in <module>
    from screenlayout.gui import main
  File "/usr/lib/python3.11/site-packages/screenlayout/gui.py", line 76, in <module>
    class Application:
  File "/usr/lib/python3.11/site-packages/screenlayout/gui.py", line 185, in Application
    @actioncallback
     ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/screenlayout/gui.py", line 48, in actioncallback
    argnames = inspect.getargspec(function)[0]
               ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

**Comment by bryteise** [comment]
Updated arandr version which has the fix for this.

**Comment by wheerdam** [comment]
Fixed in 38300
