### ISSUE TITLE
40480 - docker-compose fails with TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'

### ISSUE THREAD

**Issue by phedders** [clearlinux/distribution#3007]
In 40480 I cannot run docker-compose with down/up

`Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3.12/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
           ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'
`

Reverting to 40470 fixes it (until I get auto upgraded again!)

**Comment by nobbysheep** [comment]
+1 .. have also downgraded via `sudo swupd verify --fix -m 40470 --picky`

**Comment by lkmikkel** [comment]
Seems docker-compose has stopped receiving updates. Compose v2 has replaced it.
https://docs.docker.com/compose/install/linux/#install-the-plugin-manually

**Comment by nobbysheep** [comment]
So .. manual install or will this be sorted in up and coming update?

**Comment by puneetse** [comment]
The standalone docker-compose also works as a temporary workaround:
https://docs.docker.com/compose/install/standalone/

**Comment by lixiaodong** [comment]
> +1 .. have also downgraded via `sudo swupd verify --fix -m 40470 --picky`

ubuntu system cant install swupd command.

**Comment by lixiaodong** [comment]
> Seems docker-compose has stopped receiving updates. Compose v2 has replaced it. https://docs.docker.com/compose/install/linux/#install-the-plugin-manually

i fix it by install the plugin manually.
but this document it's not all right .
1:download the command line executable file
wget https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64
2.rename it to docker-compose
mv docker-compose-linux-x86_64  docker-compose 
3.then copy it to /usr/bin/docker-compose
cp docker-compose /usr/bin/docker-compose

hope this steps helps you ,bro.

**Comment by fenrus75** [comment]
sorry for the delay -- we're a bit on a skeleton crew during the holidays

for now I've downgraded the docker python package back to what it was in 40470 (it got updated in 480)

**Comment by Nurlan199206** [comment]
@lixiaodong thank you! it's works

**Comment by paccoe** [comment]
It worked the first time.. later i remove the container and start up again and sadly the same error than previously.
Thanks anyway.

**Comment by phedders** [comment]
I guess we are still waiting for docker compose v2 for this to be closed? Otherwise I will close this for now and perhaps open a ticket requesting docker compose v2.

**Comment by vitorzg** [comment]
I found the solution thanks to @lixiaodong. Thanks 

https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64
