### ISSUE TITLE
dstat goes wrong

### ISSUE THREAD

**Issue by Tiaonmmn** [clearlinux/distribution#3054]
I use `swupd bundle-add performance-tools` to install dstat command. After install, dstat doesn't run normally,errors occured:
```
/usr/bin/dstat:758: SyntaxWarning: invalid escape sequence '\d'
  self.diskfilter = re.compile('^([hsv]d[a-z]+\d+|cciss/c\d+d\d+p\d+|dm-\d+|md\d+|mmcblk\d+p\d0|VxVM\d+)$')
/usr/bin/dstat:844: SyntaxWarning: invalid escape sequence '\d'
  self.diskfilter = re.compile('^([hsv]d[a-z]+\d+|cciss/c\d+d\d+p\d+|dm-\d+|md\d+|mmcblk\d+p\d0|VxVM\d+)$')
/usr/bin/dstat:929: SyntaxWarning: invalid escape sequence '\d'
  self.diskfilter = re.compile('^([hsv]d[a-z]+\d+|cciss/c\d+d\d+p\d+|dm-\d+|md\d+|mmcblk\d+p\d0|VxVM\d+)$')
/usr/bin/dstat:930: SyntaxWarning: invalid escape sequence '\('
  self.regexp = re.compile('^\((\d+),(\d+)\):\(\d+,\d+,(\d+),\d+,(\d+)\)$')
/usr/bin/dstat:1181: SyntaxWarning: invalid escape sequence '\d'
  self.diskfilter = re.compile('^([hsv]d[a-z]+\d+|cciss/c\d+d\d+p\d+|dm-\d+|md\d+|mmcblk\d+p\d0|VxVM\d+)$')
/usr/bin/dstat:1327: SyntaxWarning: invalid escape sequence '\d'
  self.totalfilter = re.compile('^(lo|bond\d+|face|.+\.\d+)$')
/usr/bin/dstat:2332: SyntaxWarning: invalid escape sequence '\d'
  search = re.compile('^cpu\d+')
/usr/bin/dstat:2349: SyntaxWarning: invalid escape sequence '\d'
  m = re.match('ide/host(\d)/bus(\d)/target(\d)/lun(\d)/disc', device)
/usr/bin/dstat:2356: SyntaxWarning: invalid escape sequence '\d'
  m = re.match('cciss/(c\dd\d)', device)
You did not select any stats, using -cdngy by default.
Traceback (most recent call last):
  File "/usr/bin/dstat", line 2825, in <module>
    main()
  File "/usr/bin/dstat", line 2684, in main
    scheduler.run()
  File "/usr/lib/python3.12/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "/usr/bin/dstat", line 2782, in perform
    line = line + o.show() + o.showend(totlist, vislist)
                  ^^^^^^^^
  File "/usr/bin/dstat", line 515, in show
    if isinstance(self.val[name], collections.Sequence) and not isinstance(self.val[name], six.string_types):
                                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Sequence'
```

**Comment by bryteise** [comment]
Oof dstat isn't maintained any more in any place I see. Unfortunately that means we are having to drop it. This likely has been broken for awhile.
