### ISSUE TITLE
Input Remapper not starting

### ISSUE THREAD

**Issue by Aqua1ung** [clearlinux/distribution#3228]
Context: CL 42780
Issue: input-remapper doesn't start, https://github.com/sezanzeb/input-remapper/issues/1016

Log:
```

Dec 12 22:55:05 DadsGram systemd[2116]: Started app-gnome-input\x2dremapper\x2dgtk-6608.scope.
Dec 12 22:55:05 DadsGram input-remapper-gtk.desktop[6608]: input-remapper-gtk 2.0.1  https://github.com/sezanzeb/input-remapper
Dec 12 22:55:05 DadsGram input-remapper-gtk.desktop[6608]: python-evdev 1.7.1
Dec 12 22:55:07 DadsGram polkitd[687]: Operator of unix-session:2 successfully authenticated as unix-user:dad to gain TEMPORARY authorization for action inputremapper for unix-process:6608:742760 [/usr/bin/python3 /usr/bin/input-remapper>
Dec 12 22:55:07 DadsGram pkexec[6616]: pam_unix(polkit-1:session): session opened for user root(uid=0) by dad(uid=1000)
Dec 12 22:55:07 DadsGram pkexec[6616]: dad: Executing command [USER=root] [TTY=unknown] [CWD=/home/dad] [COMMAND=/usr/bin/input-remapper-control --command start-reader-service]
Dec 12 22:55:07 DadsGram input-remapper-gtk.desktop[6616]: Done
Dec 12 22:55:07 DadsGram input-remapper-gtk.desktop[6608]: Starting the service
Dec 12 22:55:07 DadsGram pkexec[6643]: pam_unix(polkit-1:session): session opened for user root(uid=0) by dad(uid=1000)
Dec 12 22:55:07 DadsGram pkexec[6643]: dad: Executing command [USER=root] [TTY=unknown] [CWD=/home/dad] [COMMAND=/usr/bin/input-remapper-control --command start-daemon]
Dec 12 22:55:07 DadsGram input-remapper-gtk.desktop[6643]: Done
Dec 12 22:55:07 DadsGram input-remapper-gtk.desktop[6651]: ERROR: "/home/dad/.config/input-remapper-2/config.json" does not exist
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6651]: ERROR: "/home/dad/.config/input-remapper-2/config.json" does not exist
Dec 12 22:55:08 DadsGram kernel: input-remapper-[6651]: segfault at 55d8f5dab985 ip 000055ddbc3066de sp 00007ffcbfd12730 error 4 cpu 0 in libgobject-2.0.so.0.8200.3[326de,55ddbc2e4000+5a000] likely on CPU 0 (core 0, socket 0)
Dec 12 22:55:08 DadsGram kernel: Code: 44 e2 fd ff 0f 1f 84 00 00 00 00 00 41 57 41 56 41 55 41 54 55 53 48 83 ec 18 48 85 ff 74 3d 48 8b 07 48 89 fb 48 85 c0 74 32 <48> 8b 00 48 3d fc 03 00 00 77 57 48 c1 e8 02 48 8d 15 2c 9a 05 00
Dec 12 22:55:08 DadsGram systemd[1]: Started systemd-coredump@2-6657-0.service.
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6642]: Found "Sleep Button", "Video Bus", "Wireless hotkeys", "LG WMI hotkeys", "AT Translated Set 2 keyboard", "04CA00B1:00 04CA:00B1 Mouse", "Generic USB Audio", "TESmart DKS202-P24",>
Dec 12 22:55:08 DadsGram systemd-coredump[6658]: [🡕] Process 6651 (input-remapper-) of user 0 dumped core.
                                                 
                                                 Stack trace of thread 6651:
                                                 #0  0x000055ddbc3066de g_type_check_instance_is_fundamentally_a (libgobject-2.0.so.0 + 0x326de)
                                                 #1  0x000055ddbc420018 g_source_callback_unref (libglib-2.0.so.0 + 0x88018)
                                                 #2  0x000055ddbc42229f g_source_destroy_internal (libglib-2.0.so.0 + 0x8a29f)
                                                 #3  0x000055ddbc430db0 g_main_dispatch (libglib-2.0.so.0 + 0x98db0)
                                                 #4  0x000055ddbc4e03bd g_main_context_dispatch_unlocked (libglib-2.0.so.0 + 0x1483bd)
                                                 #5  0x000055ddbc431d5f g_main_loop_run (libglib-2.0.so.0 + 0x99d5f)
                                                 #6  0x000055ddbc2c4052 ffi_call_unix64 (libffi.so.8 + 0xc052)
                                                 #7  0x000055ddbc2c255d ffi_call_int (libffi.so.8 + 0xa55d)
                                                 #8  0x000055ddbc2bd2ad ffi_call (libffi.so.8 + 0x52ad)
                                                 #9  0x000055ddbc5ba224 pygi_invoke_c_callable (_gi.cpython-313-x86_64-linux-gnu.so + 0x3a224)
                                                 #10 0x000055ddbc5b84bd pygi_function_cache_invoke (_gi.cpython-313-x86_64-linux-gnu.so + 0x384bd)
                                                 #11 0x000055ddbc5a6f30 _callable_info_call (_gi.cpython-313-x86_64-linux-gnu.so + 0x26f30)
                                                 #12 0x000055ddbdff151c _PyObject_MakeTpCall (python3.13 + 0x19351c)
                                                 #13 0x000055ddbe00996b _PyEval_EvalFrameDefault (python3.13 + 0x1ab96b)
                                                 #14 0x000055ddbe0c7c29 PyEval_EvalCode (python3.13 + 0x269c29)
                                                 #15 0x000055ddbe0ea490 run_eval_code_obj (python3.13 + 0x28c490)
                                                 #16 0x000055ddbe0e4f5c run_mod (python3.13 + 0x286f5c)
                                                 #17 0x000055ddbe10e005 pyrun_file (python3.13 + 0x2b0005)
                                                 #18 0x000055ddbe10cb7c _PyRun_SimpleFileObject (python3.13 + 0x2aeb7c)
                                                 #19 0x000055ddbe10ef5a _PyRun_AnyFileObject (python3.13 + 0x2b0f5a)
                                                 #20 0x000055ddbe0fc1f4 pymain_run_file_obj (python3.13 + 0x29e1f4)
                                                 #21 0x000055ddbe0b7ee8 Py_BytesMain (python3.13 + 0x259ee8)
                                                 #22 0x000055ddbda29fc7 __libc_start_call_main (libc.so.6 + 0x29fc7)
                                                 #23 0x000055ddbda2a085 __libc_start_main_impl (libc.so.6 + 0x2a085)
                                                 #24 0x000055ddbe0b7321 _start (python3.13 + 0x259321)
                                                 
                                                 Stack trace of thread 6654:
                                                 #0  0x000055ddbdb1b06e __GI_ppoll (libc.so.6 + 0x11b06e)
                                                 #1  0x000055ddbc4e0371 ppoll (libglib-2.0.so.0 + 0x148371)
                                                 #2  0x000055ddbc42fddc g_main_context_iteration (libglib-2.0.so.0 + 0x97ddc)
                                                 #3  0x000055ddbc47d288 g_thread_proxy (libglib-2.0.so.0 + 0xe5288)
                                                 #4  0x000055ddbda9b572 start_thread (libc.so.6 + 0x9b572)
                                                 #5  0x000055ddbdb28438 __clone3 (libc.so.6 + 0x128438)
                                                 
                                                 Stack trace of thread 6655:
                                                 #0  0x000055ddbdb1b06e __GI_ppoll (libc.so.6 + 0x11b06e)
                                                 #1  0x000055ddbc4e0371 ppoll (libglib-2.0.so.0 + 0x148371)
                                                 #2  0x000055ddbc431d5f g_main_loop_run (libglib-2.0.so.0 + 0x99d5f)
                                                 #3  0x000055ddbb1051d6 gdbus_shared_thread_func (libgio-2.0.so.0 + 0x1991d6)
                                                 #4  0x000055ddbc47d288 g_thread_proxy (libglib-2.0.so.0 + 0xe5288)
                                                 #5  0x000055ddbda9b572 start_thread (libc.so.6 + 0x9b572)
                                                 #6  0x000055ddbdb28438 __clone3 (libc.so.6 + 0x128438)
                                                 
                                                 Stack trace of thread 6653:
                                                 #0  0x000055ddbdb25cb9 syscall (libc.so.6 + 0x125cb9)
                                                 #1  0x000055ddbc4826af g_cond_wait_impl (libglib-2.0.so.0 + 0xea6af)
                                                 #2  0x000055ddbc47d288 g_thread_proxy (libglib-2.0.so.0 + 0xe5288)
                                                 #3  0x000055ddbda9b572 start_thread (libc.so.6 + 0x9b572)
                                                 #4  0x000055ddbdb28438 __clone3 (libc.so.6 + 0x128438)
                                                 ELF object binary architecture: AMD x86-64
Dec 12 22:55:08 DadsGram systemd[1]: systemd-coredump@2-6657-0.service: Deactivated successfully.
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]: Traceback (most recent call last):
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:   File "/usr/bin/input-remapper-gtk", line 89, in <module>
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:     daemon = start_processes()
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:   File "/usr/bin/input-remapper-gtk", line 53, in start_processes
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:     return Daemon.connect()
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:            ~~~~~~~~~~~~~~^^
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:   File "/usr/lib/python3.13/site-packages/inputremapper/daemon.py", line 265, in connect
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:     interface.set_config_dir(get_config_path(), timeout=2)
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:     ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:   File "/usr/lib/python3.13/site-packages/pydbus/proxy_method.py", line 72, in __call__
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:     ret = instance._bus.con.call_sync(
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:             instance._bus_name, instance._path,
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:             self._iface_name, self.__name__, GLib.Variant(self._sinargs, args), GLib.VariantType.new(self._soutargs),
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:             0, timeout_to_glib(timeout), None).unpack()
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]:      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 12 22:55:08 DadsGram input-remapper-gtk.desktop[6608]: gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (4)
```

**Comment by K1ngfish3r** [comment]
`ERROR: "/home/dad/.config/input-remapper-2/config.json" does not exist`
does it exist or is python bugging out
EDIT: my bad, probably exists.
https://github.com/sezanzeb/input-remapper/issues/1013#issuecomment-2538688004
fix from arch is to update glib2 update to version 2.82.3-3 

EDIT2: https://gitlab.archlinux.org/archlinux/packaging/packages/glib2/-/commit/89137ab46f9f2293e571b1173cd5f64a11129278
patch inside this commit
https://gitlab.archlinux.org/archlinux/packaging/packages/glib2/-/raw/89137ab46f9f2293e571b1173cd5f64a11129278/0002-Revert-gdbus-Fix-leak-of-method-invocation-when-regi.patch

**Comment by K1ngfish3r** [comment]
glib2 got an update https://download.gnome.org/sources/glib/2.82/glib-2.82.4.tar.xz
CL will just update directly to 2.82.4 rather than inserting patch

**Comment by Aqua1ung** [comment]
> fix from arch is to update glib2 update to version 2.82.3-3

Thanks! [It looks like that might be it](https://github.com/sezanzeb/input-remapper/issues/1016#issuecomment-2542271332), though I'd be happy to wait until @fenrus75 or any of the other guys issue a `glib` update in the new CL version.

**Comment by ephut** [comment]
Updated, waiting to be in a release this week.
