### ISSUE TITLE
Can we please have i3 desktop bundle?

### ISSUE THREAD

**Issue by unixbhaskar** [clearlinux/distribution#55]
I have requested it before, but it was on early stage. Kindly provide or consider the i3 desktop bundle. Not everyone is Gnome fan nor use Xfce(in spite of its lightweight nature and usefulness). 

All I am trying to say, please try to provide that bundle.

**Comment by ahkok** [comment]
After packaging a few dependencies, I'm running into a complete failure to build due to automake blowing up entirely. No idea how to actually fix the underlying breakage at this point. 

```
+ autoreconf -v --install --force
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:119: installing './ar-lib'
configure.ac:60: installing './compile'
configure.ac:7: installing './config.guess'
configure.ac:7: installing './config.sub'
configure.ac:8: installing './install-sh'
configure.ac:8: installing './missing'
Makefile.am:229: warning: '%'-style pattern rules are a GNU make extension
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
autoreconf: Leaving directory `.'
+ ./configure --build=x86_64-generic-linux-gnu --host=x86_64-generic-linux-gnu --target=x86_64-clr-linux-gnu --program-prefix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/bin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/usr/com --mandir=/usr/share/man --infodir=/usr/share/info --disable-static
configure: WARNING: unrecognized options: --disable-static
checking build system type... x86_64-generic-linux-gnu
checking host system type... x86_64-generic-linux-gnu
checking target system type... x86_64-clr-linux-gnu
continue configure in default builddir "./x86_64-clr-linux-gnu"
....exec /bin/sh .././configure "--srcdir=.." "--enable-builddir=x86_64-clr-linux-gnu" "linux
gnu"
configure: WARNING: unrecognized options: --disable-static
checking build system type... x86_64-generic-linux-gnu
checking host system type... x86_64-generic-linux-gnu
checking target system type... x86_64-clr-linux-gnu
checking for gsed... sed
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for gawk... (cached) gawk
checking for GNU make... make
checking for a sed that does not truncate output... /usr/bin/sed
checking whether to build with code coverage support... no
checking whether to enable debugging... no
checking for style of include used by make... GNU
checking for x86_64-generic-linux-gnu-gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for mode_t... yes
checking for off_t... yes
checking for pid_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for pid_t... (cached) yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking whether lstat correctly handles trailing slash... yes
checking for working strnlen... yes
checking for atexit... yes
checking for dup2... yes
checking for ftruncate... yes
checking for getcwd... yes
checking for gettimeofday... yes
checking for localtime_r... yes
checking for memchr... yes
checking for memset... yes
checking for mkdir... yes
checking for rmdir... yes
checking for setlocale... yes
checking for socket... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strndup... yes
checking for strrchr... yes
checking for strspn... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
checking for library containing floor... -lm
checking for library containing ev_run... -lev
checking for library containing shm_open... -lrt
checking for library containing iconv_open... none required
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for x86_64-generic-linux-gnu-pkg-config... /usr/bin/x86_64-generic-linux-gnu-pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libstartup-notification-1.0... yes
checking for xcb xcb-xkb xcb-xinerama xcb-randr... yes
checking for xcb-event xcb-util... yes
checking for xcb-cursor... yes
checking for xcb-keysyms... yes
checking for xcb-icccm... yes
checking for xcb-xrm... yes
checking for xkbcommon xkbcommon-x11... yes
checking for yajl... yes
checking for libpcre >= 8.10... yes
checking for cairo >= 1.14.4 pangocairo... yes
checking for gawk... (cached) gawk
checking how to run the C preprocessor... gcc -E
checking whether make sets $(MAKE)... (cached) yes
checking for x86_64-generic-linux-gnu-ranlib... gcc-ranlib
checking whether ln -s works... yes
checking for asciidoc... no
checking for xmlto... no
checking for pod2man... /usr/bin/pod2man
checking for x86_64-generic-linux-gnu-ar... gcc-ar
checking the archiver (gcc-ar) interface... ar
checking CFLAGS for maximum warnings... -Wall
checking whether C compiler accepts -Wunused-value... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking paths.h usability... yes
checking paths.h presence... yes
checking for paths.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating testcases/lib/i3test.pm
config.status: creating man/asciidoc.conf
config.status: creating testcases/complete-run.pl
config.status: creating config.h
config.status: executing buildir commands
config.status: create top_srcdir/Makefile guessed from local Makefile
config.status: build in x86_64-clr-linux-gnu (HOST=)
config.status: executing depfiles commands
configure: WARNING: unrecognized options: --disable-static
--------------------------------------------------------------------------------
build configured:
  i3 version:             4.15 (2018-03-10)
  is release version:     yes
  build manpages:         no
  build docs:             no
  enable debug flags:     no
  code coverage:          no
  enabled sanitizers:     
To compile, run:
  cd /builddir/build/BUILD/i3-4.15/x86_64-clr-linux-gnu && make -j8
--------------------------------------------------------------------------------
+ make -j8
Makefile:2693: warning: overriding recipe for target 'libi3/libi3_a-dpi.o'
Makefile:1385: warning: ignoring old recipe for target 'libi3/libi3_a-dpi.o'
Makefile:2717: warning: overriding recipe for target 'libi3/libi3_a-draw_util.o'
Makefile:1396: warning: ignoring old recipe for target 'libi3/libi3_a-draw_util.o'
Makefile:2741: warning: overriding recipe for target 'libi3/libi3_a-fake_configure_notify.o'
Makefile:1407: warning: ignoring old recipe for target 'libi3/libi3_a-fake_configure_notify.o'
Makefile:2765: warning: overriding recipe for target 'libi3/libi3_a-font.o'
Makefile:1418: warning: ignoring old recipe for target 'libi3/libi3_a-font.o'
Makefile:2789: warning: overriding recipe for target 'libi3/libi3_a-format_placeholders.o'
Makefile:1429: warning: ignoring old recipe for target 'libi3/libi3_a-format_placeholders.o'
Makefile:2813: warning: overriding recipe for target 'libi3/libi3_a-get_colorpixel.o'
Makefile:1440: warning: ignoring old recipe for target 'libi3/libi3_a-get_colorpixel.o'
Makefile:2837: warning: overriding recipe for target 'libi3/libi3_a-get_config_path.o'
Makefile:1451: warning: ignoring old recipe for target 'libi3/libi3_a-get_config_path.o'
Makefile:2861: warning: overriding recipe for target 'libi3/libi3_a-get_exe_path.o'
Makefile:1462: warning: ignoring old recipe for target 'libi3/libi3_a-get_exe_path.o'
Makefile:2885: warning: overriding recipe for target 'libi3/libi3_a-get_mod_mask.o'
Makefile:1473: warning: ignoring old recipe for target 'libi3/libi3_a-get_mod_mask.o'
Makefile:2909: warning: overriding recipe for target 'libi3/libi3_a-get_process_filename.o'
Makefile:1484: warning: ignoring old recipe for target 'libi3/libi3_a-get_process_filename.o'
Makefile:2933: warning: overriding recipe for target 'libi3/libi3_a-get_visualtype.o'
Makefile:1495: warning: ignoring old recipe for target 'libi3/libi3_a-get_visualtype.o'
Makefile:2957: warning: overriding recipe for target 'libi3/libi3_a-ipc_connect.o'
Makefile:1506: warning: ignoring old recipe for target 'libi3/libi3_a-ipc_connect.o'
Makefile:2981: warning: overriding recipe for target 'libi3/libi3_a-ipc_recv_message.o'
Makefile:1517: warning: ignoring old recipe for target 'libi3/libi3_a-ipc_recv_message.o'
Makefile:3005: warning: overriding recipe for target 'libi3/libi3_a-ipc_send_message.o'
Makefile:1528: warning: ignoring old recipe for target 'libi3/libi3_a-ipc_send_message.o'
Makefile:3029: warning: overriding recipe for target 'libi3/libi3_a-is_debug_build.o'
Makefile:1539: warning: ignoring old recipe for target 'libi3/libi3_a-is_debug_build.o'
Makefile:3053: warning: overriding recipe for target 'libi3/libi3_a-mkdirp.o'
Makefile:1550: warning: ignoring old recipe for target 'libi3/libi3_a-mkdirp.o'
Makefile:3077: warning: overriding recipe for target 'libi3/libi3_a-resolve_tilde.o'
Makefile:1561: warning: ignoring old recipe for target 'libi3/libi3_a-resolve_tilde.o'
Makefile:3101: warning: overriding recipe for target 'libi3/libi3_a-root_atom_contents.o'
Makefile:1572: warning: ignoring old recipe for target 'libi3/libi3_a-root_atom_contents.o'
Makefile:3125: warning: overriding recipe for target 'libi3/libi3_a-safewrappers.o'
Makefile:1583: warning: ignoring old recipe for target 'libi3/libi3_a-safewrappers.o'
Makefile:3149: warning: overriding recipe for target 'libi3/libi3_a-string.o'
Makefile:1594: warning: ignoring old recipe for target 'libi3/libi3_a-string.o'
Makefile:3173: warning: overriding recipe for target 'libi3/libi3_a-strndup.o'
Makefile:1605: warning: ignoring old recipe for target 'libi3/libi3_a-strndup.o'
Makefile:3197: warning: overriding recipe for target 'libi3/libi3_a-ucs2_conversion.o'
Makefile:1616: warning: ignoring old recipe for target 'libi3/libi3_a-ucs2_conversion.o'
Makefile:3221: warning: overriding recipe for target 'src/i3-assignments.o'
Makefile:1708: warning: ignoring old recipe for target 'src/i3-assignments.o'
Makefile:3245: warning: overriding recipe for target 'src/i3-bindings.o'
Makefile:1719: warning: ignoring old recipe for target 'src/i3-bindings.o'
Makefile:3269: warning: overriding recipe for target 'src/i3-click.o'
Makefile:1730: warning: ignoring old recipe for target 'src/i3-click.o'
Makefile:3293: warning: overriding recipe for target 'src/i3-commands.o'
Makefile:1741: warning: ignoring old recipe for target 'src/i3-commands.o'
Makefile:3317: warning: overriding recipe for target 'src/i3-commands_parser.o'
Makefile:1752: warning: ignoring old recipe for target 'src/i3-commands_parser.o'
Makefile:3341: warning: overriding recipe for target 'src/i3-con.o'
Makefile:1763: warning: ignoring old recipe for target 'src/i3-con.o'
Makefile:3365: warning: overriding recipe for target 'src/i3-config.o'
Makefile:1774: warning: ignoring old recipe for target 'src/i3-config.o'
Makefile:3389: warning: overriding recipe for target 'src/i3-config_directives.o'
Makefile:1785: warning: ignoring old recipe for target 'src/i3-config_directives.o'
Makefile:3413: warning: overriding recipe for target 'src/i3-config_parser.o'
Makefile:1796: warning: ignoring old recipe for target 'src/i3-config_parser.o'
Makefile:3437: warning: overriding recipe for target 'src/i3-display_version.o'
Makefile:1807: warning: ignoring old recipe for target 'src/i3-display_version.o'
Makefile:3461: warning: overriding recipe for target 'src/i3-ewmh.o'
Makefile:1818: warning: ignoring old recipe for target 'src/i3-ewmh.o'
Makefile:3485: warning: overriding recipe for target 'src/i3-fake_outputs.o'
Makefile:1829: warning: ignoring old recipe for target 'src/i3-fake_outputs.o'
Makefile:3509: warning: overriding recipe for target 'src/i3-floating.o'
Makefile:1840: warning: ignoring old recipe for target 'src/i3-floating.o'
Makefile:3533: warning: overriding recipe for target 'src/i3-handlers.o'
Makefile:1851: warning: ignoring old recipe for target 'src/i3-handlers.o'
Makefile:3557: warning: overriding recipe for target 'src/i3-ipc.o'
Makefile:1862: warning: ignoring old recipe for target 'src/i3-ipc.o'
Makefile:3581: warning: overriding recipe for target 'src/i3-key_press.o'
Makefile:1873: warning: ignoring old recipe for target 'src/i3-key_press.o'
Makefile:3605: warning: overriding recipe for target 'src/i3-load_layout.o'
Makefile:1884: warning: ignoring old recipe for target 'src/i3-load_layout.o'
Makefile:3629: warning: overriding recipe for target 'src/i3-log.o'
Makefile:1895: warning: ignoring old recipe for target 'src/i3-log.o'
Makefile:3653: warning: overriding recipe for target 'src/i3-main.o'
Makefile:1906: warning: ignoring old recipe for target 'src/i3-main.o'
Makefile:3677: warning: overriding recipe for target 'src/i3-manage.o'
Makefile:1917: warning: ignoring old recipe for target 'src/i3-manage.o'
Makefile:3701: warning: overriding recipe for target 'src/i3-match.o'
Makefile:1928: warning: ignoring old recipe for target 'src/i3-match.o'
Makefile:3725: warning: overriding recipe for target 'src/i3-move.o'
Makefile:1939: warning: ignoring old recipe for target 'src/i3-move.o'
Makefile:3749: warning: overriding recipe for target 'src/i3-output.o'
Makefile:1950: warning: ignoring old recipe for target 'src/i3-output.o'
Makefile:3773: warning: overriding recipe for target 'src/i3-randr.o'
Makefile:1961: warning: ignoring old recipe for target 'src/i3-randr.o'
Makefile:3797: warning: overriding recipe for target 'src/i3-regex.o'
Makefile:1972: warning: ignoring old recipe for target 'src/i3-regex.o'
RPM build errors:
Makefile:3821: warning: overriding recipe for target 'src/i3-render.o'
Makefile:1983: warning: ignoring old recipe for target 'src/i3-render.o'
Makefile:3845: warning: overriding recipe for target 'src/i3-resize.o'
Makefile:1994: warning: ignoring old recipe for target 'src/i3-resize.o'
Makefile:3869: warning: overriding recipe for target 'src/i3-restore_layout.o'
Makefile:2005: warning: ignoring old recipe for target 'src/i3-restore_layout.o'
Makefile:3893: warning: overriding recipe for target 'src/i3-scratchpad.o'
Makefile:2016: warning: ignoring old recipe for target 'src/i3-scratchpad.o'
Makefile:3917: warning: overriding recipe for target 'src/i3-sd-daemon.o'
Makefile:2027: warning: ignoring old recipe for target 'src/i3-sd-daemon.o'
Makefile:3941: warning: overriding recipe for target 'src/i3-sighandler.o'
Makefile:2038: warning: ignoring old recipe for target 'src/i3-sighandler.o'
Makefile:3965: warning: overriding recipe for target 'src/i3-startup.o'
Makefile:2049: warning: ignoring old recipe for target 'src/i3-startup.o'
Makefile:3989: warning: overriding recipe for target 'src/i3-tree.o'
Makefile:2060: warning: ignoring old recipe for target 'src/i3-tree.o'
Makefile:4013: warning: overriding recipe for target 'src/i3-util.o'
Makefile:2071: warning: ignoring old recipe for target 'src/i3-util.o'
Makefile:4037: warning: overriding recipe for target 'src/i3-version.o'
Makefile:2082: warning: ignoring old recipe for target 'src/i3-version.o'
Makefile:4061: warning: overriding recipe for target 'src/i3-window.o'
Makefile:2093: warning: ignoring old recipe for target 'src/i3-window.o'
Makefile:4085: warning: overriding recipe for target 'src/i3-workspace.o'
Makefile:2104: warning: ignoring old recipe for target 'src/i3-workspace.o'
Makefile:4109: warning: overriding recipe for target 'src/i3-x.o'
Makefile:2115: warning: ignoring old recipe for target 'src/i3-x.o'
Makefile:4133: warning: overriding recipe for target 'src/i3-xcb.o'
Makefile:2126: warning: ignoring old recipe for target 'src/i3-xcb.o'
Makefile:4157: warning: overriding recipe for target 'src/i3-xcursor.o'
Makefile:2137: warning: ignoring old recipe for target 'src/i3-xcursor.o'
Makefile:4181: warning: overriding recipe for target 'src/i3-xinerama.o'
Makefile:2148: warning: ignoring old recipe for target 'src/i3-xinerama.o'
Makefile:4205: warning: overriding recipe for target 'i3-config-wizard/i3_config_wizard_i3_config_wizard-main.o'
Makefile:2193: warning: ignoring old recipe for target 'i3-config-wizard/i3_config_wizard_i3_config_wizard-main.o'
Makefile:4229: warning: overriding recipe for target 'i3-dump-log/i3_dump_log_i3_dump_log-main.o'
Makefile:2238: warning: ignoring old recipe for target 'i3-dump-log/i3_dump_log_i3_dump_log-main.o'
Makefile:4253: warning: overriding recipe for target 'i3-input/i3_input_i3_input-keysym2ucs.o'
Makefile:2283: warning: ignoring old recipe for target 'i3-input/i3_input_i3_input-keysym2ucs.o'
Makefile:4277: warning: overriding recipe for target 'i3-input/i3_input_i3_input-main.o'
Makefile:2294: warning: ignoring old recipe for target 'i3-input/i3_input_i3_input-main.o'
Makefile:4301: warning: overriding recipe for target 'i3-msg/i3_msg_i3_msg-main.o'
Makefile:2339: warning: ignoring old recipe for target 'i3-msg/i3_msg_i3_msg-main.o'
Makefile:4325: warning: overriding recipe for target 'i3-nagbar/i3_nagbar_i3_nagbar-main.o'
Makefile:2384: warning: ignoring old recipe for target 'i3-nagbar/i3_nagbar_i3_nagbar-main.o'
Makefile:4349: warning: overriding recipe for target 'i3bar/src/i3bar_i3bar-child.o'
Makefile:2429: warning: ignoring old recipe for target 'i3bar/src/i3bar_i3bar-child.o'
Makefile:4373: warning: overriding recipe for target 'i3bar/src/i3bar_i3bar-config.o'
Makefile:2440: warning: ignoring old recipe for target 'i3bar/src/i3bar_i3bar-config.o'
Makefile:4397: warning: overriding recipe for target 'i3bar/src/i3bar_i3bar-ipc.o'
Makefile:2451: warning: ignoring old recipe for target 'i3bar/src/i3bar_i3bar-ipc.o'
Makefile:4421: warning: overriding recipe for target 'i3bar/src/i3bar_i3bar-main.o'
Makefile:2462: warning: ignoring old recipe for target 'i3bar/src/i3bar_i3bar-main.o'
Makefile:4445: warning: overriding recipe for target 'i3bar/src/i3bar_i3bar-mode.o'
Makefile:2473: warning: ignoring old recipe for target 'i3bar/src/i3bar_i3bar-mode.o'
Makefile:4469: warning: overriding recipe for target 'i3bar/src/i3bar_i3bar-outputs.o'
Makefile:2484: warning: ignoring old recipe for target 'i3bar/src/i3bar_i3bar-outputs.o'
Makefile:4493: warning: overriding recipe for target 'i3bar/src/i3bar_i3bar-parse_json_header.o'
Makefile:2495: warning: ignoring old recipe for target 'i3bar/src/i3bar_i3bar-parse_json_header.o'
Makefile:4517: warning: overriding recipe for target 'i3bar/src/i3bar_i3bar-workspaces.o'
Makefile:2506: warning: ignoring old recipe for target 'i3bar/src/i3bar_i3bar-workspaces.o'
Makefile:4541: warning: overriding recipe for target 'i3bar/src/i3bar_i3bar-xcb.o'
Makefile:2517: warning: ignoring old recipe for target 'i3bar/src/i3bar_i3bar-xcb.o'
Makefile:4565: warning: overriding recipe for target 'src/test_commands_parser-commands_parser.o'
Makefile:2551: warning: ignoring old recipe for target 'src/test_commands_parser-commands_parser.o'
Makefile:4589: warning: overriding recipe for target 'src/test_config_parser-config_parser.o'
Makefile:2574: warning: ignoring old recipe for target 'src/test_config_parser-config_parser.o'
Makefile:4613: warning: overriding recipe for target 'testcases/test_inject_randr15-inject_randr1.5.o'
Makefile:2619: warning: ignoring old recipe for target 'testcases/test_inject_randr15-inject_randr1.5.o'
Makefile:4981: *** unterminated variable reference.  Stop.
error: Bad exit status from /var/tmp/rpm-tmp.jPpt7Z (%build)
    Bad exit status from /var/tmp/rpm-tmp.jPpt7Z (%build)
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/i3.spec 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 526, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/i3.spec 
LEAVE do --> EXCEPTION RAISED
```

**Comment by ahkok** [comment]
@stapelberg you wouldn't have to have any idea, would you? The offending Makefile lines are obviously broken:

```
4981 am--fnord am--fnord-all $(TEST_LOGS) $(TEST_LOGS:
4982         @ HOST="$(HOST)" \
4983         ; test ".$$HOST" = "." && HOST=` sh /builddir/build/BUILD/i3-4.15/config.guess ` \
4984         ; BUILD=` grep "^#### $$HOST " Makefile | sed -e 's/.*|//' ` \
4985         ; use=` basename "$@" -all `; n=` echo $$BUILD | wc -w ` \
4986         ; echo "MAKE $$HOST : $$n * $@"; if test "$$n" -eq "0" ; then : \
4987         ; BUILD=` grep "^####.*|" Makefile |tail -1| sed -e 's/.*|//' ` ; fi \
4988         ; test ".$$BUILD" = "." && BUILD="." \
4989         ; test "$$use" = "$@" && BUILD=` echo "$$BUILD" | tail -1 ` \
4990         ; for i in $$BUILD ; do test ".$$i" = "." && continue \
4991         ; (cd "$$i" && test ! -f configure && $(MAKE) $$use) || exit; done
```

**Comment by ahkok** [comment]
Happens either with `autoreconf -vif` or using `./configure &&` etc.

**Comment by ahkok** [comment]
Found: https://github.com/Airblader/i3/issues/145

**Comment by stapelberg** [comment]
Haven’t run into this before. Might be worth bringing up on the automake mailing list? If it’s something we’re doing wrong in our usage of auto*, I’ll happily accept fixes.

**Comment by ahkok** [comment]
@stapelberg I'm as confused here as the previous reporter, so that's probably worth doing.

**Comment by ahkok** [comment]
@unixbhaskar should be packaged up ready for testing as `desktop-i3`. In order for it to be useful, you probably need several other bundles though (`os-utils-gui` or `desktop`, probably)

**Comment by unixbhaskar** [comment]
@ahkok  Thanks a bunch for the pain you and others took. Certainly, give it a shot and let you know if something uncanny come to my eyes.

**Comment by unixbhaskar** [comment]
I could not find the i3 stuff on this page:  https://clearlinux.org/documentation/clear-linux/reference/bundles/available-bundles

Probably the package is not ready yet. Kindly let us know when it is available.

O btw, I have already these bundles in my system 
`
root@ClearLinux_21:11:03_Thu May 03:~ # swupd bundle-list
swupd-client bundle list 3.16.0
   Copyright (C) 2012-2018 Intel Corporation

bootloader
c-basic
containers-basic
containers-basic-dev
containers-virt
containers-virt-dev
cryptography
desktop
desktop-apps
desktop-apps-extras
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
dev-utils
dev-utils-dev
editors
editors-dev
emacs
go-basic
go-basic-dev
kernel-container
kernel-native
koji
kvm-host
libX11client
mail-utils
mail-utils-dev
mixer
network-basic
network-basic-dev
openssh-server
os-clr-on-clr
os-clr-on-clr-dev
os-core
os-core-dev
os-core-update
os-core-update-dev
os-installer
os-utils-gui
package-utils
performance-tools
perl-basic
perl-basic-dev
pnp-tools-basic
python-basic
python-basic-dev
python2-basic
python3-basic
shells
storage-utils
storage-utils-dev
sysadmin-basic
sysadmin-basic-dev
tcl-basic
telemetrics
user-basic
vim
web-server-basic
xfce4-desktop


`

**Comment by matthewrsj** [comment]
`desktop-i3` is not out yet. It will be available in the next OS release later this morning (or afternoon if this build doesn't make it out).

**Comment by unixbhaskar** [comment]
@matthewrsj Awesome man!

**Comment by matthewrsj** [comment]
Also, it should be noted that https://clearlinux.org/documentation/clear-linux/reference/bundles/available-bundles is very out of date. I opened an issue for that here: https://github.com/clearlinux/clear-linux-documentation/issues/126

**Comment by ahkok** [comment]
There's a small fix coming for `i3status` but otherwise I think it's working correctly, so I'm closing this.
