### ISSUE TITLE
Settings crash

### ISSUE THREAD

**Issue by MattiaVerticchio** [clearlinux/distribution#556]
**Describe the bug**
Settings application crashes while trying to change system language.
```Shell
# gnome-control-center

(gnome-control-center:2618): GnomeDesktop-CRITICAL **: 22:28:23.812: gnome_get_country_from_code: assertion 'code != NULL' failed

(gnome-control-center:2618): GnomeDesktop-CRITICAL **: 22:28:23.813: gnome_get_country_from_code: assertion 'code != NULL' failed

(gnome-control-center:2618): GLib-GObject-CRITICAL **: 22:28:31.310: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Segmentation fault (core dumped)
```

**To Reproduce**
1. Open the settings;
2. Select Region & Language;
3. Select Language;
4. Scroll down and load more languages;
5. Type in the search bar (E.G. *it*);
6. Settings crashes.

**Expected behavior**
The Settings app should be able to load the searched languages.

**Environment:**
 - Clear Linux OS version:
```Shell
# cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28390
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
```
 - Bundles:
```Shell
# sudo swupd bundle-list
NetworkManager
acpica-unix2
alsa-utils
baobab
bc
binutils
bison
boot-encrypted
bootloader
bootloader-extras
c-basic
cheese
cloc
cpio
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
dev-utils
devpkg-base
devpkg-llvm
diffutils
docutils
dosfstools
editors
emacs
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
fwupdate
gdb
gedit
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gstreamer
gvim
gzip
hardware-printing
hardware-uefi
htop
icdiff
inotify-tools
iproute2
iptables
irssi
joe
kbd
kernel-install
kernel-native
kvm-host
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libstdcpp
libva-utils
linux-firmware
linux-firmware-extras
linux-firmware-wifi
linux-tools
llvm
mail-utils
make
minicom
mutt
nasm
nautilus
network-basic
nfs-utils
notmuch
offlineimap
openblas
openldap
openssh-server
openssl
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
pmdk
polkit
powertop
pulseaudio
pygobject
python2-basic
python3-basic
qemu-guest-additions
samba
seahorse
shells
smartmontools
storage-utils
strace
sudo
sysadmin-basic
telemetrics
thermal_daemon
tmux
totem
tzdata
unzip
user-basic
valgrind
vim
weechat
wget
which
wpa_supplicant
x11-server
xemacs
xfsprogs
xz
znc
zsh
zstd
```

**Comment by mrkz** [comment]
running gnome-control-center with GDB shows the following bt:
```
(gdb) bt
#0  0x00000000004d70ff in language_visible (row=0x19c0f50, user_data=0x18d8300) at ../panels/common/cc-language-chooser.c:221                      
#1  0x00007ffff76b783f in gtk_list_box_apply_filter (row=0x19c0f50, box=0xf7b220) at gtklistbox.c:2279                                             
#2  0x00007ffff76b783f in gtk_list_box_apply_filter_all (box=0xf7b220) at gtklistbox.c:2279                                                        
#3  0x00007ffff76b783f in gtk_list_box_invalidate_filter (box=0xf7b220, box=<optimized out>) at gtklistbox.c:1260                                  
#4  0x00000000004d7026 in filter_changed (chooser=0x18d8300) at ../panels/common/cc-language-chooser.c:284                                         
#5  0x00007ffff7d6b8e3 in _g_closure_invoke_va
    (param_types=0x0, n_params=0, args=0x7fffffffbac0, instance=0xf16de0, return_value=0x0, closure=0x1af5e10) at ../gobject/gclosure.c:873        
#6  0x00007ffff7d6b8e3 in g_signal_emit_valist (instance=0xf16de0, signal_id=<optimized out>, detail=<optimized out>, var_args=0x7fffffffbac0)     
    at ../gobject/gsignal.c:3300
#7  0x00007ffff7d6003d in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3447 
#8  0x00007ffff7817e82 in gtk_search_entry_changed_timeout_cb (user_data=<error reading variable: value has been optimized out>)                   
    at gtksearchentry.c:295
#9  0x00007ffff7c847dc in g_timeout_dispatch
    (source=0x1d15420, callback=<optimized out>, user_data=<optimized out>, source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at ../glib/gmain.c:4678
#10 0x00007ffff7c86839 in g_main_dispatch (context=0x8b86d0) at ../glib/gmain.c:3189                                                               
#11 0x00007ffff7c86839 in g_main_context_dispatch (context=0x8b86d0) at ../glib/gmain.c:3854                                                       
#12 0x00007ffff7c86c38 in g_main_context_iterate.isra.80.lto_priv.628
    (context=context@entry=0x8b86d0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:3927                 
#13 0x00007ffff7c86c7b in g_main_context_iteration (context=0x8b86d0, may_block=1) at ../glib/gthread.c:1003                                       
#14 0x00007ffff7e7100d in g_application_run (application=0x9d5320, argc=argc@entry=2, argv=argv@entry=0x7fffffffbe78) at ../gio/gapplication.c:2516
#15 0x000000000045bdc7 in main (argc=<optimized out>, argv=<optimized out>) at ../shell/main.c:70
```

**Comment by AthenasJimenez** [comment]
Fix in the oven, should be available by the end of the day.

**Comment by AthenasJimenez** [comment]
Fixed on release 28560.
