### ISSUE TITLE
virt-manager bundle have missing dependency of LibvirtGLib

### ISSUE THREAD

**Issue by curantes** [clearlinux/distribution#588]
**Describe the bug**
I installed the virt-manager bundle but got below error in a terminal when trying to debug why virt-manager would not start.

```
$ virt-manager
Traceback (most recent call last):
  File "/usr/share/virt-manager/virt-manager", line 30, in <module>
    gi.require_version('LibvirtGLib', '1.0')
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace LibvirtGLib not available
```
I did a `sudo swupd search LibvirtGLib` and found it to be included in virt-viewer bundle. After adding this bundle I could start virt-manager.

**To Reproduce**
1. On a fresh install of CL install virt-manager bundle
2. Try to start virt-manager

**Expected behavior**
Install virt-manager bundle should be enough to get all required dependencies to start virt-manager

**Environment (please complete the following information):**
 - Clear Linux OS version: 28560
 - Bundles: 
```
Babel
NetworkManager
Sphinx
acpica-unix2
alsa-utils
baobab
bc
binutils
bison
bootloader
c-basic
cabextract
cheese
cloc
clr-network-troubleshooter
containers-basic
cpio
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
dev-utils
dev-utils-dev
devpkg-LVM2
devpkg-SDL
devpkg-acl
devpkg-alsa-lib
devpkg-apr
devpkg-at-spi2-atk
devpkg-at-spi2-core
devpkg-atk
devpkg-attr
devpkg-audit
devpkg-base
devpkg-boost
devpkg-cairo
devpkg-compat-enchant-soname1
devpkg-compat-fuse-soname2
devpkg-cryptsetup
devpkg-curl
devpkg-cyrus-sasl
devpkg-dbus
devpkg-dbus-glib
devpkg-e2fsprogs
devpkg-elfutils
devpkg-expat
devpkg-fontconfig
devpkg-freetype
devpkg-fribidi
devpkg-fuse
devpkg-gdk-pixbuf
devpkg-glib
devpkg-gmime
devpkg-gnutls
devpkg-gobject-introspection
devpkg-googletest
devpkg-graphite
devpkg-gsl
devpkg-gtk
devpkg-gtk-doc
devpkg-gtk3
devpkg-guile
devpkg-harfbuzz
devpkg-hwloc
devpkg-icu4c
devpkg-ipmctl
devpkg-ipset
devpkg-iptables
devpkg-json-c
devpkg-kmod
devpkg-krb5
devpkg-libX11
devpkg-libXScrnSaver
devpkg-libXau
devpkg-libXcursor
devpkg-libXdamage
devpkg-libXdmcp
devpkg-libXext
devpkg-libXfixes
devpkg-libXft
devpkg-libXmu
devpkg-libXpm
devpkg-libXres
devpkg-libXt
devpkg-libXtst
devpkg-libXv
devpkg-libXvMC
devpkg-libXxf86misc
devpkg-libXxf86vm
devpkg-libarchive
devpkg-libassuan
devpkg-libcap
devpkg-libcap-ng
devpkg-libcgroup
devpkg-libdrm
devpkg-libepoxy
devpkg-libevent
devpkg-libffi
devpkg-libgpg-error
devpkg-libidn
devpkg-libidn2
devpkg-libinput
devpkg-libjpeg-turbo
devpkg-libmicrohttpd
devpkg-libmnl
devpkg-libnetfilter_conntrack
devpkg-libnetfilter_cthelper
devpkg-libnetfilter_cttimeout
devpkg-libnetfilter_queue
devpkg-libnfnetlink
devpkg-libnftnl
devpkg-libnl
devpkg-libpcap
devpkg-libpciaccess
devpkg-libpipeline
devpkg-libpng
devpkg-libpthread-stubs
devpkg-librsvg
devpkg-libseccomp
devpkg-libssh2
devpkg-libtasn1
devpkg-libtirpc
devpkg-libunwind
devpkg-libusb
devpkg-libuser
devpkg-libva
devpkg-libxcb
devpkg-libxkbcommon
devpkg-libxml2
devpkg-libxslt
devpkg-libzip
devpkg-llvm
devpkg-lua
devpkg-lz4
devpkg-mesa
devpkg-metrics-discovery
devpkg-multipath-tools
devpkg-ncurses
devpkg-ndctl
devpkg-nettle
devpkg-nftables
devpkg-nghttp2
devpkg-nspr
devpkg-nss
devpkg-ntfs-3g
devpkg-open-iscsi
devpkg-openmpi
devpkg-openssl
devpkg-openvswitch
devpkg-p11-kit
devpkg-pacrunner
devpkg-pango
devpkg-parted
devpkg-pciutils
devpkg-pcre
devpkg-pcre2
devpkg-pixman
devpkg-pkcs11-helper
devpkg-pmdk
devpkg-popt
devpkg-postgresql
devpkg-procps-ng
devpkg-qtbase
devpkg-qttools
devpkg-rdma-core
devpkg-readline
devpkg-sqlite-autoconf
devpkg-startup-notification
devpkg-subunit
devpkg-systemd
devpkg-telemetrics-client
devpkg-tiff
devpkg-userspace-rcu
devpkg-util-linux
devpkg-util-macros
devpkg-wayland
devpkg-wayland-protocols
devpkg-xapian-core
devpkg-xcb-proto
devpkg-xorgproto
devpkg-xtrans
devpkg-xz
devpkg-zlib
devpkg-zstd
diffoscope
diffutils
dnf
docbook-utils
docutils
dosfstools
doxygen
editors
emacs
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
fwupdate
gdb
gedit
git
gjs
glibc-locale
global
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
go-basic
gpgme
graphviz
gstreamer
gvim
gzip
hardware-printing
hardware-uefi
htop
httpd
icdiff
inotify-tools
intltool
iproute2
iptables
irssi
joe
kbd
kernel-install
kernel-native
koji
kvm-host
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libarchive
libglib
libstdcpp
libva-utils
libxml2
libxslt
linux-firmware
linux-firmware-extras
linux-firmware-wifi
linux-tools
llvm
mail-utils
mail-utils-dev
make
minicom
mixer
mkosi
mutt
nasm
nautilus
network-basic
network-basic-dev
nfs-utils
nginx
nodejs-basic
notmuch
offlineimap
openblas
openldap
openssh-server
openssl
os-clr-on-clr
os-core
os-core-dev
os-core-update
os-core-update-dev
os-core-webproxy
os-installer
p11-kit
package-builder
package-utils
parallel
parted
patch
perl-basic
perl-basic-dev
plzip
pmdk
polkit
postgresql
powertop
pulseaudio
pygobject
python2-basic
python3-basic
qemu-guest-additions
qt-basic
qt-core
ruby-basic
samba
scons
seahorse
smartmontools
storage-utils
storage-utils-dev
strace
subversion
sudo
sysadmin-basic
sysadmin-basic-dev
telemetrics
texinfo
texlive
thermal_daemon
tmux
totem
tzdata
unbundle
unzip
valgrind
vim
virt-manager
web-server-basic
weechat
wget
which
wpa_supplicant
x11-server
xemacs
xfsprogs
xz
yasm
znc
zstd
```

**Comment by curantes** [comment]
I noticed there was a virt-manager-gui bundle as well. Seems a bit confusing. Is it not better to have one bundle that have both gui and tui?

**Comment by fenrus75** [comment]
(fixing the missing dep)

the gui ends up pulling a lot of core gui libraries in and ends up big...
some folks really like just tui for small instances, hence us splitting
gui/tui (pretty much across the OS, we even do that for vim and emacs)
