### ISSUE TITLE
dnf bundle doesn't work on its own

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#598]
**Describe the bug**
Installing the *dnf* bundle doesn't allow dnf to run on its own. If I add *package-utils* it works.

**To Reproduce**
1.  docker run -it clearlinux
2.  swupd bundle-add dnf
3. dnf 
4. (crashes)

**Expected behavior**
The **dnf** bundle should run on its own and contain and runtime dependencies.

**Additional context**

Only installing the *dnf* bundle

```
root@5c13b0d6bb19 / # swupd bundle-add dnf
Downloading packs...
        ...14%
Extracting dnf pack for version 28410
        ...28%
Extracting pygobject pack for version 28250
        ...42%
Extracting python3-basic pack for version 28350
        ...57%
Extracting libX11client pack for version 28360
        ...100%

Extracting lib-opengl pack for version 28360

Extracting lib-openssl pack for version 28150

Extracting file pack for version 28410
Starting download of remaining update content. This may take a while...
        ...100%
Finishing download of update content...
Installing bundle(s) files...
        ...100%
Calling post-update helper scripts.
Successfully installed 1 bundle
root@5c13b0d6bb19 / # dnf
Traceback (most recent call last):
  File "/usr/bin/dnf", line 57, in <module>
    from dnf.cli import main
  File "/usr/lib/python3.7/site-packages/dnf/__init__.py", line 30, in <module>
    import dnf.base
  File "/usr/lib/python3.7/site-packages/dnf/base.py", line 31, in <module>
    from dnf.comps import CompsQuery
  File "/usr/lib/python3.7/site-packages/dnf/comps.py", line 32, in <module>
    import dnf.util
  File "/usr/lib/python3.7/site-packages/dnf/util.py", line 29, in <module>
    import dnf.callback
  File "/usr/lib/python3.7/site-packages/dnf/callback.py", line 22, in <module>
    import dnf.yum.rpmtrans
  File "/usr/lib/python3.7/site-packages/dnf/yum/rpmtrans.py", line 26, in <module>
    import rpm
ModuleNotFoundError: No module named 'rpm'
```

After installing *package-utils*
```
root@5c13b0d6bb19 / # swupd bundle-add package-utils
Downloading packs...
        ...25%
Extracting package-utils pack for version 28360
        ...50%
Extracting perl-basic pack for version 28230
        ...75%
Extracting python2-basic pack for version 28360
        ...100%

Extracting openblas pack for version 27900
Starting download of remaining update content. This may take a while...
        ...100%
Finishing download of update content...
Installing bundle(s) files...
        ...100%
Calling post-update helper scripts.
Successfully installed 1 bundle
root@5c13b0d6bb19 / # dnf
IniParser: Can't open file
Unable to detect release version (use '--releasever' to specify release version)
usage: dnf [options] COMMAND

List of Main Commands:
```

**Comment by fenrus75** [comment]
hmm what would you expect to use dnf for?

**Comment by phmccarty** [comment]
If I didn't have larger bundles installed that already provide developer tools (like `package-utils`), I imagine being able to run `dnf repoquery ...` is still useful in isolation.

**Comment by puneetse** [comment]
@phmccarty got it. I'm looking to build docker container that runs dnf to repoquery and reposync an external repo to a local volume for later use and manipulation.

**Comment by phmccarty** [comment]
@puneetse try again in 28650 or newer, since the `python-rpm` package was added to the `dnf` bundle.

**Comment by puneetse** [comment]
Works great! Thank you.

**Comment by tpleavitt** [comment]
@puneetse , thanks for the verification, closing
