### ISSUE TITLE
Broken Python module "skimage"

### ISSUE THREAD

**Issue by thiagomacieira** [clearlinux/distribution#697]
```
$ python3 -c import\ skimage
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/skimage/__init__.py", line 127, in <module>
    from .util.dtype import (img_as_float32,
  File "/usr/lib/python3.7/site-packages/skimage/util/__init__.py", line 6, in <module>
    from .apply_parallel import apply_parallel
  File "/usr/lib/python3.7/site-packages/skimage/util/apply_parallel.py", line 8, in <module>
    import dask.array as da
  File "/usr/lib/python3.7/site-packages/dask/array/__init__.py", line 5, in <module>
    from .core import (Array, block, concatenate, stack, from_array, store,
  File "/usr/lib/python3.7/site-packages/dask/array/core.py", line 46, in <module>
    from ..bytes.core import get_mapper, get_fs_token_paths
  File "/usr/lib/python3.7/site-packages/dask/bytes/__init__.py", line 4, in <module>
    from .core import read_bytes, open_files
  File "/usr/lib/python3.7/site-packages/dask/bytes/core.py", line 11, in <module>
    from .compression import seekable_files, files as compress_files
  File "/usr/lib/python3.7/site-packages/dask/bytes/compression.py", line 31, in <module>
    compress['snappy'] = snappy.compress
AttributeError: module 'snappy' has no attribute 'compress'
```
There's no error when trying to do `import snappy`.

Bundle list:
Babel
NetworkManager
NetworkManager-basic
NetworkManager-extras
Sphinx
acl
acpica-unix2
alsa-utils
baobab
bc
bcc
binutils
bison
c-basic
cabextract
ceph
cheese
cloc
cloud-api
clr-network-troubleshooter
containers-basic
cpio
cryptography
curl
desktop
desktop-apps
desktop-assets
desktop-dev
desktop-gnomelibs
desktop-locales
dev-utils
dev-utils-dev
devpkg-GConf
devpkg-LVM2
devpkg-LibRaw
devpkg-NetworkManager
devpkg-R
devpkg-SDL
devpkg-SDL2
devpkg-SDL2_image
devpkg-acl
devpkg-alsa-lib
devpkg-appstream-glib
devpkg-apr
devpkg-at-spi2-atk
devpkg-at-spi2-core
devpkg-atk
devpkg-atkmm
devpkg-attr
devpkg-audit
devpkg-babl
devpkg-base
devpkg-bluez
devpkg-boost
devpkg-brotli
devpkg-cairo
devpkg-cairomm
devpkg-cheese
devpkg-clutter
devpkg-clutter-gst
devpkg-cmrt
devpkg-cogl
devpkg-colord
devpkg-compat-enchant-soname1
devpkg-compat-fuse-soname2
devpkg-compat-gegl
devpkg-compat-gtksourceview-soname3
devpkg-cryptsetup
devpkg-cups-filters
devpkg-curl
devpkg-cyrus-sasl
devpkg-dbus
devpkg-dbus-glib
devpkg-e2fsprogs
devpkg-elfutils
devpkg-enchant
devpkg-evolution
devpkg-evolution-data-server
devpkg-exiv2
devpkg-expat
devpkg-fftw
devpkg-flac
devpkg-flatpak
devpkg-font-util
devpkg-fontconfig
devpkg-freeglut
devpkg-freetype
devpkg-fribidi
devpkg-fuse
devpkg-fwupd
devpkg-gcab
devpkg-gcr
devpkg-gdk-pixbuf
devpkg-gdm
devpkg-gegl
devpkg-geoclue
devpkg-geocode-glib
devpkg-gexiv2
devpkg-gfbgraph
devpkg-gimp
devpkg-gjs
devpkg-glib
devpkg-glibmm
devpkg-glu
devpkg-gmime
devpkg-gnome-autoar
devpkg-gnome-bluetooth
devpkg-gnome-desktop
devpkg-gnome-menus
devpkg-gnome-online-accounts
devpkg-gnome-panel
devpkg-gnome-settings-daemon
devpkg-gnome-software
devpkg-gnome-video-effects
devpkg-gnutls
devpkg-gobject-introspection
devpkg-googletest
devpkg-gperftools
devpkg-graphite
devpkg-grilo
devpkg-grilo-plugins
devpkg-gsettings-desktop-schemas
devpkg-gsl
devpkg-gsound
devpkg-gspell
devpkg-gst-plugins-bad
devpkg-gst-plugins-base
devpkg-gstreamer
devpkg-gtk
devpkg-gtk-doc
devpkg-gtk3
devpkg-gtkmm3
devpkg-gtkplus
devpkg-gtkspell3
devpkg-guile
devpkg-gutenprint
devpkg-harfbuzz
devpkg-hwloc
devpkg-icu4c
devpkg-ipmctl
devpkg-ipset
devpkg-iptables
devpkg-iso-codes
devpkg-json-c
devpkg-json-glib
devpkg-kmod
devpkg-krb5
devpkg-lcms2
devpkg-libX11
devpkg-libXScrnSaver
devpkg-libXau
devpkg-libXcursor
devpkg-libXdamage
devpkg-libXdmcp
devpkg-libXext
devpkg-libXfixes
devpkg-libXfont
devpkg-libXfont2
devpkg-libXft
devpkg-libXmu
devpkg-libXpm
devpkg-libXres
devpkg-libXt
devpkg-libXtst
devpkg-libXv
devpkg-libXvMC
devpkg-libXxf86misc
devpkg-libXxf86vm
devpkg-libarchive
devpkg-libassuan
devpkg-libatasmart
devpkg-libcanberra
devpkg-libcap
devpkg-libcap-ng
devpkg-libcgroup
devpkg-libconfig
devpkg-libcroco
devpkg-libdatrie
devpkg-libdazzle
devpkg-libdrm
devpkg-libepoxy
devpkg-libevdev
devpkg-libevent
devpkg-libexif
devpkg-libffi
devpkg-libfontenc
devpkg-libgcrypt
devpkg-libgd
devpkg-libgdata
devpkg-libgee
devpkg-libgnomekbd
devpkg-libgpg-error
devpkg-libgphoto2
devpkg-libgsystem
devpkg-libgtop
devpkg-libgudev
devpkg-libgusb
devpkg-libgweather
devpkg-libical
devpkg-libidn
devpkg-libidn2
devpkg-libinput
devpkg-libiscsi
devpkg-libjpeg-turbo
devpkg-libmediaart
devpkg-libmicrohttpd
devpkg-libmnl
devpkg-libmspack
devpkg-libmtp
devpkg-libmypaint
devpkg-libndp
devpkg-libnetfilter_conntrack
devpkg-libnetfilter_cthelper
devpkg-libnetfilter_cttimeout
devpkg-libnetfilter_queue
devpkg-libnfnetlink
devpkg-libnftnl
devpkg-libnl
devpkg-libnotify
devpkg-liboauth
devpkg-libogg
devpkg-libosinfo
devpkg-libpcap
devpkg-libpciaccess
devpkg-libpeas
devpkg-libpinyin
devpkg-libpipeline
devpkg-libpng
devpkg-libpsl
devpkg-libpthread-stubs
devpkg-librsvg
devpkg-libsamplerate
devpkg-libsass
devpkg-libsctp
devpkg-libseccomp
devpkg-libsecret
devpkg-libsigcplusplus
devpkg-libsmbios
devpkg-libsoup
devpkg-libspectre
devpkg-libsrtp
devpkg-libssh2
devpkg-libstoragemgmt
devpkg-libtasn1
devpkg-libthai
devpkg-libtirpc
devpkg-libunwind
devpkg-libusb
devpkg-libuser
devpkg-libva
devpkg-libwacom
devpkg-libwebp
devpkg-libwnck3
devpkg-libxcb
devpkg-libxkbcommon
devpkg-libxkbfile
devpkg-libxklavier
devpkg-libxml2
devpkg-libxslt
devpkg-libyami
devpkg-libzip
devpkg-llvm
devpkg-lua
devpkg-lz4
devpkg-mariadb
devpkg-mediasdk
devpkg-mesa
devpkg-metacity
devpkg-metrics-discovery
devpkg-mozjs52
devpkg-mozjs60
devpkg-mpg123
devpkg-multipath-tools
devpkg-mutter
devpkg-nautilus
devpkg-ncurses
devpkg-ndctl
devpkg-nettle
devpkg-network-manager-applet
devpkg-newt
devpkg-nftables
devpkg-nghttp2
devpkg-nspr
devpkg-nss
devpkg-ntfs-3g
devpkg-open-iscsi
devpkg-opencv
devpkg-openmpi
devpkg-openssl
devpkg-openvswitch
devpkg-opus
devpkg-orc
devpkg-ostree
devpkg-p11-kit
devpkg-pacrunner
devpkg-pango
devpkg-pangomm
devpkg-parted
devpkg-pciutils
devpkg-pcre
devpkg-pcre2
devpkg-pipewire
devpkg-pixman
devpkg-pkcs11-helper
devpkg-pmdk
devpkg-popt
devpkg-postgresql
devpkg-procps-ng
devpkg-pulseaudio
devpkg-pygobject
devpkg-qpdf
devpkg-qt3d
devpkg-qtbase
devpkg-qtdeclarative
devpkg-qtlocation
devpkg-qtsvg
devpkg-qttools
devpkg-qtwebchannel
devpkg-rdma-core
devpkg-readline
devpkg-rest
devpkg-shared-mime-info
devpkg-sqlite-autoconf
devpkg-startup-notification
devpkg-subunit
devpkg-systemd
devpkg-talloc
devpkg-tbb
devpkg-telemetrics-client
devpkg-tiff
devpkg-uhttpmock
devpkg-userspace-rcu
devpkg-util-linux
devpkg-util-macros
devpkg-v4l-utils
devpkg-vala
devpkg-wayland
devpkg-wayland-protocols
devpkg-webkitgtk
devpkg-woff2
devpkg-xapian-core
devpkg-xcb-proto
devpkg-xcb-util-cursor
devpkg-xdg-desktop-portal
devpkg-xf86-input-wacom
devpkg-xkbcomp
devpkg-xkeyboard-config
devpkg-xorg-server
devpkg-xorgproto
devpkg-xtrans
devpkg-xz
devpkg-zlib
devpkg-zstd
diffoscope
diffutils
dnf
docbook-utils
docutils
dosfstools
doxygen
dpdk
duperemove
editors
emacs
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fontforge
fonts-basic
fonttools
fuse
fwupdate
gdb
gedit
gimp
git
gjs
glibc-locale
global
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
go-basic
gpgme
graphviz
gstreamer
gvim
gzip
hardware-printing
htop
httpd
icdiff
icecream
inkscape
inotify-tools
intltool
iotop
iperf
iproute2
iptables
irssi
joe
jq
kbd
kde-frameworks5
kdiff3
kernel-install
koji
kvm-host
less
lftp
lib-imageformat
lib-opengl
lib-openssl
lib-qt5webengine
lib-samba
libX11client
libarchive
libglib
libstdcpp
libva-utils
libxml2
libxslt
linux-firmware-extras
linux-firmware-wifi
linux-tools
llvm
mail-utils
mail-utils-dev
make
man-pages
mercurial
minicom
mixer
mkosi
mutt
nasm
nautilus
net-tools
network-basic
network-basic-dev
nfs-utils
nginx
nodejs-basic
notmuch
offlineimap
openblas
openldap
openssh-server
openssl
openvswitch
os-clr-on-clr
os-core
os-core-dev
os-core-update
os-core-update-dev
os-core-webproxy
os-installer
os-testsuite
p11-kit
package-builder
package-utils
parallel
parted
patch
performance-tools
perl-basic
perl-basic-dev
perl-extras
plzip
pmdk
polkit
postgresql
powertop
procps-ng
pulseaudio
pwgen
pxe-server
pygobject
python-extras
python2-basic
python3-basic
python3-tcl
qt-basic
qt-basic-dev
qt-core
ruby-basic
samba
scons
seahorse
smartmontools
sqlite
storage-utils
storage-utils-dev
strace
subversion
sudo
sysadmin-basic
sysadmin-basic-dev
sysstat
tcl-basic
texinfo
texlive
thermal_daemon
tmux
totem
tzdata
unbundle
unzip
valgrind
vim
web-server-basic
webkitgtk
weechat
wget
which
wpa_supplicant
x11-server
xemacs
xfsprogs
xz
yasm
znc
zsh
zstd

**Comment by bryteise** [comment]
Hrm I'm unable to replicate this on 29280. Looking at the code I can see why you'd hit this error if you have the snappy module available but it is in a weird state given it ignores ImportError but not AttributeError when doing the import.

**Comment by amygilliam1** [comment]
@thiagomacieira , is this still an issue?
