### ISSUE TITLE
Package request: git-lfs

### ISSUE THREAD

**Issue by znmeb** [clearlinux/distribution#759]

**Comment by bwarden** [comment]
This is golang with lots of dependencies, so it will have to go in the queue for manual attention.

**Comment by nsauzede** [comment]
what is the status ? Is there an available git-lfs bundle for ClearLinux ? I can't find one

**Comment by bwarden** [comment]
@bryteise Is our `go` build support sufficient to add this? https://github.com/git-lfs/git-lfs/releases/download/v2.10.0/git-lfs-v2.10.0.tar.gz

**Comment by bryteise** [comment]
Looks like they ship a vendor directory using go modules so while the dependencies are not in good shape we can force it to work with the current autospec.

**Comment by bwarden** [comment]
The build process attempts to download additional non-versioned dependencies, so it's still not quite compatible with autospec.
```
go: github.com/alexbrainman/sspi@v0.0.0-20180125232955-4729b3d4d858: Get https://proxy.golang.org/github.com/alexbrainman/sspi/@v/v0.0.0-20180125232955-4729b3d4d858.mod: dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:40212->[::1]:53: read: connection refused
go: github.com/alexbrainman/sspi@v0.0.0-20180125232955-4729b3d4d858: Get https://proxy.golang.org/github.com/alexbrainman/sspi/@v/v0.0.0-20180125232955-4729b3d4d858.mod: dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:56033->[::1]:53: read: connection refused
git-lfs: skipping fmt, no goimports found at `goimports` ...
go generate github.com/git-lfs/git-lfs/commands
go: github.com/alexbrainman/sspi@v0.0.0-20180125232955-4729b3d4d858: Get https://proxy.golang.org/github.com/alexbrainman/sspi/@v/v0.0.0-20180125232955-4729b3d4d858.mod: dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:35818->[::1]:53: read: connection refused
```

**Comment by phmccarty** [comment]
Is it building with `go build -mod=vendor`?

**Comment by bwarden** [comment]
No, we tried `make` after `go mod vendor` failed:

```
+ go mod vendor
go: github.com/alexbrainman/sspi@v0.0.0-20180125232955-4729b3d4d858: reading file:///usr/share/goproxy/github.com/alexbrainman/sspi/@v/v0.0.0-20180125232955-4729b3d4d858.mod: Not Found
error: Bad exit status from /var/tmp/rpm-tmp.xGMGWs (%build)
    Bad exit status from /var/tmp/rpm-tmp.xGMGWs (%build)
RPM build errors:
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/util.py", line 742, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed:
 # /usr/bin/systemd-nspawn -q -M 1dc3564c7bb04854b279058cfd88875b -D /var/lib/mock/clear-git-lfs/root -a --capability=cap_ipc_lock --console=pipe --bind=/tmp/mock-resolv.p5rjbg0y:/etc/resolv.conf --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=en_US.UTF-8 --setenv=CCACHE_DIR=/var/tmp/ccache --setenv=CCACHE_UMASK=002 -u mockbuild bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/git-lfs.spec
```

**Comment by OpenSauce04** [comment]
The lack of this package is irritating because I need it for several of my projects
This leads to me having to manually install it by downloading a tar.gz

**Comment by bwarden** [comment]
It was a bit tricky to build in our environment due to undocumented variables (see https://src.fedoraproject.org/rpms/git-lfs/blob/rawhide/f/git-lfs.spec), but I've added it. You should see a `git-lfs` bundle in an upcoming release, or you'll get it automatically with the `dev-utils` bundle if you already have that installed.
