### ISSUE TITLE
QGIS errors on startup

### ISSUE THREAD

**Issue by znmeb** [clearlinux/distribution#764]
When I start QGIS Desktop, I get the following complaints:

```
Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/share/qgis/python/qgis/__init__.py", line 72, in 
    from qgis.PyQt import QtCore
  File "/usr/share/qgis/python/qgis/PyQt/QtCore.py", line 26, in 
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5'


Python version:
3.7.3 (default, Apr 21 2019, 03:57:40) 
[GCC 9.0.1 20190420 (experimental) gcc-8-branch@270465]

QGIS version:
3.4.2-Madeira 'Madeira', exported

Python path:
['/usr/share/qgis/python', '/home/znmeb/.local/share/QGIS/QGIS3/profiles/default/python', '/home/znmeb/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/home/znmeb/.local/lib/python3.7/site-packages', '/usr/lib/python3.7/site-packages']
```

```
An error occurred during execution of following code:
qgis.utils.uninstallErrorHook()


Traceback (most recent call last):
  File "", line 1, in 
NameError: name 'qgis' is not defined


Python version:
3.7.3 (default, Apr 21 2019, 03:57:40) 
[GCC 9.0.1 20190420 (experimental) gcc-8-branch@270465]

QGIS version:
3.4.2-Madeira 'Madeira', exported

Python path:
['/usr/share/qgis/python', '/home/znmeb/.local/share/QGIS/QGIS3/profiles/default/python', '/home/znmeb/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/home/znmeb/.local/lib/python3.7/site-packages', '/usr/lib/python3.7/site-packages']
```

**Comment by thiagomacieira** [comment]
We have PyQt5 but it doesn't appear to be in any bundle.

**Comment by thiagomacieira** [comment]
After adding the missing dependencies, I now get:
```
Traceback (most recent call last):
[...]
  File "/usr/share/qgis/python/qgis/gui/__init__.py", line 27, in <module>
    from qgis._gui import *
RuntimeError: qgis._gui cannot import type '����' from PyQt5.QtCore
```

qgis._gui is a compiled source (there's a _gui.so file), so this must getting generated from inside the compiler sources. I have no idea how to proceed.

**Comment by bryteise** [comment]
I think it may be being generated incorrectly here still but I am not sure.

**Comment by znmeb** [comment]
See my comment https://github.com/clearlinux/distribution/issues/765#issuecomment-494549121. You need to build `maker-gis` and `devpkg-gis` as integrated wholes, rather than a package at a time.
