### ISSUE TITLE
Include Spyder into python bundle

### ISSUE THREAD

**Issue by olegmikul** [clearlinux/distribution#896]
Spyder is a great Python IDE, especially for data science like tasks, with focus on data. Can Spyder be included in some Clear Linux bundle?

**Comment by CuriousCocainist** [comment]
I second that! Especially that there is no flatpack...
I think as well that together with Spyder pythonistas could use Miniconda in that bundle. Thinking about it, I'll add this request as well :)

**Comment by bryteise** [comment]
Added by @fenrus75, should be in the next release.

**Comment by CuriousCocainist** [comment]
Just installed Spyder, and it doesn't want to start...
Initially though it may have something to do with conda installed, but after removing it problem remains :(
Btw, Spyder is in version 3 and conda (yeah I was the one moaning about it before) appears to be unable to create new environments whatsoever... :(((

**Comment by lebensterben** [comment]
I can confirm this problem.
```
❯ spyder3
Traceback (most recent call last):
  File "/usr/bin/spyder3", line 2, in <module>
    from spyder.app import start
  File "/usr/lib/python3.8/site-packages/spyder/app/start.py", line 34, in <module>
    from spyder.config.manager import CONF
  File "/usr/lib/python3.8/site-packages/spyder/config/manager.py", line 17, in <module>
    from spyder.config.main import CONF_VERSION, DEFAULTS, NAME_MAP
  File "/usr/lib/python3.8/site-packages/spyder/config/main.py", line 19, in <module>
    from spyder.config.fonts import MEDIUM, SANS_SERIF
  File "/usr/lib/python3.8/site-packages/spyder/config/fonts.py", line 14, in <module>
    from spyder.config.utils import is_ubuntu
  File "/usr/lib/python3.8/site-packages/spyder/config/utils.py", line 15, in <module>
    from spyder_kernels.utils import iofuncs
ModuleNotFoundError: No module named 'spyder_kernels'
```

**Comment by phmccarty** [comment]
I recently discovered that by building spyder (`spyder-ide` package) from source, the dependency information is not generated, so we did not detect this issue when the package was originally added. (For example, `pip check` doesn't detect any issues, since the metadata isn't present.)

I added some dependencies of spyder to the repo already, like `spyder-kernels` and maybe a couple others, but `pyqtwebengine` is intentionally disabled in our `qtwebengine` package, so I'm not sure how we should proceed.
