### ISSUE TITLE
Yarn package (cli-tool) not available from cli

### ISSUE THREAD

**Issue by Akiyamka** [clearlinux/distribution#962]

**Comment by fenrus75** [comment]
s $ yarn
yarn: command not found
To install yarn your system administrator needs to do: swupd bundle-add
big-data-basic

hmmm

**Comment by fenrus75** [comment]
yarn/yarn.spec:/usr/bin/yarnpkg

but it's called yarnpkg not yarn

**Comment by Akiyamka** [comment]
> but it's called yarnpkg not yarn
hmm interesting, but why, it's always be `yarn`.  Suddenly  I get crash anyway 
```
➜ yarnpkg
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/yarn/bin/../lib/cli'
Require stack:
- /usr/lib/node_modules/yarn/bin/yarn.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/lib/node_modules/yarn/bin/yarn.js:24:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/lib/node_modules/yarn/bin/yarn.js' ]
}
```

**Comment by Akiyamka** [comment]
```
To install yarn your system administrator needs to do: swupd bundle-add big-data-basic
```
What does the node package manager have in relation to the bigdata? =)

**Comment by lebensterben** [comment]
> ```
> To install yarn your system administrator needs to do: swupd bundle-add big-data-basic
> ```
> 
> What does the node package manager have in relation to the bigdata? =)

`Hadoop` has a binary called `yarn`.

**Comment by Akiyamka** [comment]
Сurrently the workaround is:
```
curl -o- -L https://yarnpkg.com/install.sh | bash
```

**Comment by fenrus75** [comment]
I've added yarn to nodejs-basic since that seems a decent place for it
(indeed better than big-data anything)

**Comment by nsgnn** [comment]
Yarn command does not work for me after reinstalling yarn bundle. This is inside WebStorm, which autodetects my yarn install still. Error message :
```
/usr/bin/node /usr/lib/node_modules/yarn/bin/yarn.js install
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/yarn/bin/../lib/cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/yarn/bin/yarn.js:24:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

Process finished with exit code 1
```
